export const SEED_WEAR_TYPES = [
  // Garment Workspace Wear Types
  {
    id: "top_wear",
    workspace: "garment",
    code: "top_wear",
    nameEn: "Top Wear",
    nameTe: "పై దుస్తులు",
    description: "Shirts, T-shirts, Kurtis, Blouses, Tops, Hoodies, Blazers",
    icon: "Shirt",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "bottom_wear",
    workspace: "garment",
    code: "bottom_wear",
    nameEn: "Bottom Wear",
    nameTe: "కింది దుస్తులు",
    description: "Jeans, Trousers, Skirts, Pants, Trackpants",
    icon: "Scissors",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "full_wear",
    workspace: "garment",
    code: "full_wear",
    nameEn: "Full Wear",
    nameTe: "పూర్తి దుస్తులు",
    description: "Dresses, Sarees, Suits, Jumpsuits, Gowns, Sherwanis, Dhotis",
    icon: "Sparkles",
    displayOrder: 3,
    isActive: true,
  },

  // Jewelry Workspace Wear Types
  {
    id: "neck_wear",
    workspace: "jewelry",
    code: "neck_wear",
    nameEn: "Neck Wear",
    nameTe: "నెక్ వేర్",
    description: "Necklaces, Chokers, Chains, Pendants, Mangalsutras",
    icon: "Gem",
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "ear_wear",
    workspace: "jewelry",
    code: "ear_wear",
    nameEn: "Ear Wear",
    nameTe: "ఇయర్ వేర్",
    description: "Earrings, Jhumkas, Studs, Drops, Hoops",
    icon: "Sparkle",
    displayOrder: 5,
    isActive: true,
  },
  {
    id: "wrist_wear",
    workspace: "jewelry",
    code: "wrist_wear",
    nameEn: "Wrist Wear",
    nameTe: "రిస్ట్ వేర్",
    description: "Bangles, Bracelets, Kadas, Watches",
    icon: "Watch",
    displayOrder: 6,
    isActive: true,
  },
  {
    id: "hip_wear",
    workspace: "jewelry",
    code: "hip_wear",
    nameEn: "Hip Wear",
    nameTe: "హిప్ వేర్",
    description: "Vaddanams, Waistbands, Kamarbands, Hip Chains",
    icon: "Shield",
    displayOrder: 7,
    isActive: true,
  },
  {
    id: "nose_wear",
    workspace: "jewelry",
    code: "nose_wear",
    nameEn: "Nose Wear",
    nameTe: "ముక్కుపుడక",
    description: "Nose pins, Naths, Bridal Nose Rings",
    icon: "CircleDot",
    displayOrder: 8,
    isActive: true,
  },
  {
    id: "leg_wear",
    workspace: "jewelry",
    code: "leg_wear",
    nameEn: "Leg Wear",
    nameTe: "లెగ్ వేర్",
    description: "Anklets, Payals, Toe rings",
    icon: "Footprints",
    displayOrder: 9,
    isActive: true,
  },
  {
    id: "forehead_wear",
    workspace: "jewelry",
    code: "forehead_wear",
    nameEn: "Forehead Wear",
    nameTe: "నుదురు ఆభరణాలు",
    description: "Maang tikkas, Mathapattis, Borlas",
    icon: "Crown",
    displayOrder: 10,
    isActive: true,
  },
  {
    id: "other_wear",
    workspace: "jewelry",
    code: "other_wear",
    nameEn: "Other Wear",
    nameTe: "ఇతర ఆభరణాలు",
    description: "Brooches, Rings, Accessories",
    icon: "Award",
    displayOrder: 11,
    isActive: true,
  },
];
