export const SEED_WORKSPACES = [
  {
    id: "garment",
    code: "garment",
    nameEn: "Garment Studio",
    nameTe: "దుస్తుల స్టూడియో",
    description: "Apparel, sarees, lehengas, and westernwear photoshoot studio",
    icon: "Shirt",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "jewelry",
    code: "jewelry",
    nameEn: "Jewelry Studio",
    nameTe: "నగల స్టూడియో",
    description: "Precious jewelry, necklaces, earrings, and watches product studio",
    icon: "Gem",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "general",
    code: "general",
    nameEn: "General Studio",
    nameTe: "సాధారణ స్టూడియో",
    description: "General multipurpose photoshoot studio",
    icon: "Sparkles",
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "all",
    code: "all",
    nameEn: "All Workspaces",
    nameTe: "అన్ని స్టూడియోలు",
    description: "Universal assets and presets applicable to both garment and jewelry",
    icon: "Globe",
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "face",
    code: "face",
    nameEn: "Face & Model Studio",
    nameTe: "మోడల్ ఫేస్ స్టూడియో",
    description: "Model face generator and custom headshot workspace",
    icon: "ScanFace",
    displayOrder: 5,
    isActive: true,
  },
];
