/**
 * Seed data for all 100+ Garment and Jewelry Poses, Camera Angles & Face Visibility Rules
 */

export interface SeedPose {
  id: string;
  type: "pose";
  workspace: "garment" | "jewelry" | "all";
  subCategory: string; // 'full_wear', 'top_wear', 'bottom_wear', 'neckwear', 'earwear', 'wrist', 'hip', 'nose', 'finger', 'leg', 'forehead', 'partial_face', 'no_face'
  nameEn: string;
  nameTe: string;
  promptDirective: string;
  cameraFraming: string;
  faceVisibilityRule: "full_face" | "partial_face" | "no_face";
  displayOrder: number;
  isActive: boolean;
}

export const SEED_POSES: SeedPose[] = [
  // ==========================================
  // 1. GARMENT POSES (Full Wear)
  // ==========================================
  {
    id: "standing_front",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Standing Front Pose",
    nameTe: "ముందు నిలబడి (Front)",
    promptDirective: "standing straight in a polished professional catalog front pose (face fully shown in clean catalog alignment)",
    cameraFraming: "Full-length catalog shot, direct frontal camera framing capturing head to toe (face fully shown in clean catalog alignment)",
    faceVisibilityRule: "full_face",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "standing_side",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Standing Side Profile",
    nameTe: "సైడ్ ప్రొఫైల్ (Side)",
    promptDirective: "standing in an elegant three-quarter side profile showcase pose (face fully shown in 3/4 side profile view)",
    cameraFraming: "Full-body three-quarter side profile angle showcasing side silhouette and outfit fall (face fully shown in 3/4 side profile view)",
    faceVisibilityRule: "full_face",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "standing_three_quarter",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Three-Quarter Standing",
    nameTe: "మూడు వంతుల నిలబడి",
    promptDirective: "standing in an elegant three-quarter angle studio catalog pose (face fully shown in studio gaze)",
    cameraFraming: "Three-quarter camera perspective balancing full outfit drape and model posture (face fully shown in studio gaze)",
    faceVisibilityRule: "full_face",
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "walking_candid",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Walking Candid Pose",
    nameTe: "నడుస్తూ (Walking)",
    promptDirective: "captured in a dynamic, stylish walking candid street style pose (face fully shown in natural candid movement)",
    cameraFraming: "Dynamic full-body street-style candid shot with forward stride motion (face fully shown in natural movement)",
    faceVisibilityRule: "full_face",
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "sitting_chair",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Sitting on Chair",
    nameTe: "కుర్చీలో కూర్చుని (Sitting)",
    promptDirective: "sitting elegantly on a stylish studio chair in a professional catalog pose (face fully shown in poised sitting posture)",
    cameraFraming: "Full-body seated studio composition framing outfit drapes on chair (face fully shown in poised sitting posture)",
    faceVisibilityRule: "full_face",
    displayOrder: 5,
    isActive: true,
  },
  {
    id: "sitting_casual",
    type: "pose",
    workspace: "garment",
    subCategory: "full_wear",
    nameEn: "Sitting Casually",
    nameTe: "సాధారణంగా కూర్చుని",
    promptDirective: "sitting in a casual, relaxed lounge style posture, natural poise (face fully shown)",
    cameraFraming: "Relaxed full-length seated lounge framing showcasing fabric folds (face fully shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 6,
    isActive: true,
  },

  // ==========================================
  // 2. GARMENT POSES (Top Wear)
  // ==========================================
  {
    id: "top_upper_portrait",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "Upper Body Portrait",
    nameTe: "పైభాగం పోర్ట్రెయిట్",
    promptDirective: "high-chest portrait framing upper garment and shoulders (face fully shown centered in frame)",
    cameraFraming: "Upper torso portrait framing shoulders, collarline, chest, and face (face fully shown centered in frame)",
    faceVisibilityRule: "full_face",
    displayOrder: 7,
    isActive: true,
  },
  {
    id: "top_standing_mid",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "Mid-Shot Standing",
    nameTe: "మిడ్-షాట్ నిలబడి",
    promptDirective: "standing mid-length portrait framing torso down to hips (face fully shown with poised posture)",
    cameraFraming: "Mid-length camera framing from head down to hips, highlighting waistline and upper fit (face fully shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 8,
    isActive: true,
  },
  {
    id: "top_three_quarter",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "3/4 Upper Body Angle",
    nameTe: "3/4 పైభాగం యాంగిల్",
    promptDirective: "three-quarter upper body studio angle (face fully shown in 3/4 turn)",
    cameraFraming: "Three-quarter angle upper body portrait framing chest, shoulders, and sleeve length (face fully shown in 3/4 turn)",
    faceVisibilityRule: "full_face",
    displayOrder: 9,
    isActive: true,
  },
  {
    id: "top_shoulder_profile",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "Shoulder & Collar Focus",
    nameTe: "భుజం & కాలర్ ఫోకస్",
    promptDirective: "side profile shoulder angle showcasing neckline and sleeve cut (face fully shown in side profile view)",
    cameraFraming: "Side shoulder profile shot showcasing neckline cut, armholes, and back detail (face fully shown in side profile view)",
    faceVisibilityRule: "full_face",
    displayOrder: 10,
    isActive: true,
  },
  {
    id: "top_casual_cross",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "Arms Crossed Pose",
    nameTe: "చేతులు కట్టుకున్న భంగిమ",
    promptDirective: "casual crossed-arms posture highlighting chest and fit (face fully shown directly facing camera)",
    cameraFraming: "Frontal mid-shot framing crossed arms over chest and garment structure (face fully shown facing camera)",
    faceVisibilityRule: "full_face",
    displayOrder: 11,
    isActive: true,
  },
  {
    id: "top_front_direct",
    type: "pose",
    workspace: "garment",
    subCategory: "top_wear",
    nameEn: "Direct Front Chest Shot",
    nameTe: "నేరుగా ముందు ఛాతీ షాట్",
    promptDirective: "direct frontal torso alignment with symmetrical shoulders (face fully shown in frontal symmetry)",
    cameraFraming: "Symmetrical frontal upper-body shot highlighting chest pattern and collar geometry (face fully shown in direct symmetry)",
    faceVisibilityRule: "full_face",
    displayOrder: 12,
    isActive: true,
  },

  // ==========================================
  // 3. GARMENT POSES (Bottom Wear)
  // ==========================================
  {
    id: "bottom_full_leg",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "Waist-to-Ankle Shot",
    nameTe: "నడుము నుండి మడమ దాకా",
    promptDirective: "waist-to-ankle shot showcasing leg silhouette, trousers, or skirt (face partially shown or cropped above waist depending on framing height)",
    cameraFraming: "Lower body shot framing waist to ankles, prioritizing pant drape and leg silhouette (face partially shown or cropped above waist depending on framing height)",
    faceVisibilityRule: "partial_face",
    displayOrder: 13,
    isActive: true,
  },
  {
    id: "bottom_walking_step",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "Walking Step Motion",
    nameTe: "నడక అడుగు మోషన్",
    promptDirective: "walking step motion highlighting pant drape and footwear (face partially shown or cropped above waist)",
    cameraFraming: "Dynamic lower-body walking stride shot framing legs and hemline motion (face partially shown or cropped above waist)",
    faceVisibilityRule: "partial_face",
    displayOrder: 14,
    isActive: true,
  },
  {
    id: "bottom_side_leg",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "Side Leg Profile",
    nameTe: "సైడ్ కాలు ప్రొఫైల్",
    promptDirective: "side leg profile showcasing waistline, pockets, and side seams (face partially shown / lower body focus)",
    cameraFraming: "Side leg profile shot highlighting waistline, side seams, and pocket detailing (face partially shown / lower body focus)",
    faceVisibilityRule: "partial_face",
    displayOrder: 15,
    isActive: true,
  },
  {
    id: "bottom_seated_cross",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "Seated Leg Showcase",
    nameTe: "కూర్చున్న కాలు ప్రదర్శన",
    promptDirective: "seated leg showcase with crossed knees displaying fabric stretch (face partially or fully shown in relaxed seating)",
    cameraFraming: "Seated leg showcase framing crossed knees, fabric stretch, and hem finish (face partially or fully shown in relaxed seating)",
    faceVisibilityRule: "partial_face",
    displayOrder: 16,
    isActive: true,
  },
  {
    id: "bottom_3q_lower",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "3/4 Lower Body Angle",
    nameTe: "3/4 కింది శరీరం యాంగిల్",
    promptDirective: "three-quarter lower body catalog angle (face partially shown or cropped near chest)",
    cameraFraming: "Three-quarter lower body catalog framing centered on hips and trousers (face partially shown or cropped near chest)",
    faceVisibilityRule: "partial_face",
    displayOrder: 17,
    isActive: true,
  },
  {
    id: "bottom_front_stance",
    type: "pose",
    workspace: "garment",
    subCategory: "bottom_wear",
    nameEn: "Wide Stance Stride",
    nameTe: "విస్తృత నిలబడే భంగిమ",
    promptDirective: "wide stance stride showcasing fit across hips and thighs (face partially or fully shown depending on vertical crop)",
    cameraFraming: "Wide stance lower-body shot displaying fabric fall across thighs and legs (face partially or fully shown depending on vertical crop)",
    faceVisibilityRule: "partial_face",
    displayOrder: 18,
    isActive: true,
  },

  // ==========================================
  // 4. JEWELRY POSES (Neckwear)
  // ==========================================
  {
    id: "neck_collarbone",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "Neck & Collarbone Focus",
    nameTe: "మెడ & కాలర్‌బోన్ ఫోకస్",
    promptDirective: "in an intimate macro close-up portrait focusing on the neck, collarbone, and neckline (face partially shown — cropped cleanly from chin/lower lip to chest, emphasizing necklace drape)",
    cameraFraming: "Intimate macro close-up framing upper chest, collarbone, and neck (face partially shown — cropped cleanly from chin/lower lip to chest, emphasizing necklace drape)",
    faceVisibilityRule: "partial_face",
    displayOrder: 19,
    isActive: true,
  },
  {
    id: "neck_chest_portrait",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "High Chest Portrait",
    nameTe: "పై ఛాతీ పోర్ట్రెయిట్",
    promptDirective: "in a high chest beauty portrait framing neckwear over collarbone and upper chest (face fully shown or lower face framed cleanly above necklace)",
    cameraFraming: "High chest beauty portrait framing neckwear over collarbone and upper chest (face fully shown or lower face framed cleanly above necklace)",
    faceVisibilityRule: "full_face",
    displayOrder: 20,
    isActive: true,
  },
  {
    id: "neck_3q_shoulder",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "3/4 Shoulder Angle",
    nameTe: "3/4 భుజం యాంగిల్",
    promptDirective: "in a three-quarter shoulder turn highlighting neckwear angle and shoulder drape (face fully shown in 3/4 beauty angle)",
    cameraFraming: "Three-quarter shoulder turn highlighting neckwear angle and shoulder drape (face fully shown in 3/4 beauty angle)",
    faceVisibilityRule: "full_face",
    displayOrder: 21,
    isActive: true,
  },
  {
    id: "neck_royal_gaze",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "Regal Royal Posture",
    nameTe: "రాయల్ భంగిమ",
    promptDirective: "in a regal posture looking slightly upward into golden studio light (face fully shown with serene gaze)",
    cameraFraming: "Regal portrait angle with model looking slightly upward, framing neckwear and facial poise (face fully shown with serene gaze)",
    faceVisibilityRule: "full_face",
    displayOrder: 22,
    isActive: true,
  },
  {
    id: "neck_front_direct",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "Direct Front Neckline",
    nameTe: "నేరుగా నెక్లైన్ వ్యూ",
    promptDirective: "in a direct frontal close-up framing symmetrical necklace and collarbone (face fully shown or lower face framed in direct symmetry)",
    cameraFraming: "Direct frontal close-up framing symmetrical necklace and collarbone structure (face fully shown or lower face framed in direct symmetry)",
    faceVisibilityRule: "full_face",
    displayOrder: 23,
    isActive: true,
  },
  {
    id: "neck_side_drape",
    type: "pose",
    workspace: "jewelry",
    subCategory: "neck_ear",
    nameEn: "Side Angle Drape",
    nameTe: "పక్క యాంగిల్ డ్రేప్",
    promptDirective: "in a side profile neck drape angle showcasing clasp and side links (face partially shown in side profile focusing on neck and jawline)",
    cameraFraming: "Side profile neck drape angle showcasing clasp, side chainwork, and jawline (face partially shown in side profile focusing on neck and jawline)",
    faceVisibilityRule: "partial_face",
    displayOrder: 24,
    isActive: true,
  },

  // ==========================================
  // 5. JEWELRY POSES (Earwear)
  // ==========================================
  {
    id: "side_ear_profile",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "Ear Profile & Jawline",
    nameTe: "చెవి ప్రొఫైల్ & దవడ",
    promptDirective: "in an elegant side profile angle highlighting earlobe, jawline, and neck (face partially shown in side profile, focusing on ear and cheekbone)",
    cameraFraming: "Side profile beauty camera angle focusing on earlobe, cheekbone, and jawline (face partially shown in side profile, focusing on ear and cheekbone)",
    faceVisibilityRule: "partial_face",
    displayOrder: 25,
    isActive: true,
  },
  {
    id: "ear_hair_tuck",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "Hair Tucked Behind Ear",
    nameTe: "చెవి వెనుక జుట్టు తిప్పిన యాంగిల్",
    promptDirective: "with hair tucked behind ear revealing dangling earring details (face fully or partially shown in side profile angle)",
    cameraFraming: "Side angle close-up with hair tucked behind ear, framing dangling earring details (face fully or partially shown in side profile angle)",
    faceVisibilityRule: "partial_face",
    displayOrder: 26,
    isActive: true,
  },
  {
    id: "ear_head_tilt",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "Gentle Head Tilt Profile",
    nameTe: "సున్నితమైన తల వాల్చిన ప్రొఫైల్",
    promptDirective: "with a gentle head tilt showcasing earring drop length (face fully shown with graceful head angle)",
    cameraFraming: "Gentle head tilt angle showcasing earring drop length and sparkling reflections (face fully shown with graceful head angle)",
    faceVisibilityRule: "full_face",
    displayOrder: 27,
    isActive: true,
  },
  {
    id: "ear_3q_face",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "3/4 Face Framing Angle",
    nameTe: "3/4 ముఖం ఫ్రేమింగ్ యాంగిల్",
    promptDirective: "in a three-quarter face turn framing earring and cheek contour (face fully shown in 3/4 beauty gaze)",
    cameraFraming: "Three-quarter beauty portrait framing earring drop against cheek contour (face fully shown in 3/4 beauty gaze)",
    faceVisibilityRule: "full_face",
    displayOrder: 28,
    isActive: true,
  },
  {
    id: "ear_front_balanced",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "Both Ears Frontal Shot",
    nameTe: "రెండు చెవుల ముందు షాట్",
    promptDirective: "in a direct frontal portrait displaying both dangling earrings symmetrically (face fully shown centered in frame)",
    cameraFraming: "Direct frontal symmetry framing both dangling earrings equally alongside facial features (face fully shown centered in frame)",
    faceVisibilityRule: "full_face",
    displayOrder: 29,
    isActive: true,
  },
  {
    id: "ear_over_shoulder",
    type: "pose",
    workspace: "jewelry",
    subCategory: "ear_wear",
    nameEn: "Over-The-Shoulder Turn",
    nameTe: "భుజం పైనుండి చూసే యాంగిల్",
    promptDirective: "in an over-the-shoulder glance highlighting ear profile and jawline (face partially shown in over-the-shoulder view)",
    cameraFraming: "Over-the-shoulder glance framing ear profile, jawline, and back hair drape (face partially shown in over-the-shoulder view)",
    faceVisibilityRule: "partial_face",
    displayOrder: 30,
    isActive: true,
  },

  // ==========================================
  // 6. JEWELRY POSES (Wrist & Rings)
  // ==========================================
  {
    id: "wrist_hand_display",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Wrist & Arm Pose",
    nameTe: "మణికట్టు & చేయి భంగిమ",
    promptDirective: "in a refined close-up gesture focusing on hand, wrist, and forearm placement (face partially shown — softly blurred or cropped above chest, prioritizing wrist accessories)",
    cameraFraming: "Close-up hand and wrist gesture shot, framing watch dials, bangles, or bracelets (face partially shown — softly blurred or cropped above chest, prioritizing wrist accessories)",
    faceVisibilityRule: "partial_face",
    displayOrder: 31,
    isActive: true,
  },
  {
    id: "wrist_resting_lap",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Resting Hand on Lap",
    nameTe: "ఒడిలో పెట్టిన చేయి",
    promptDirective: "with hands resting gracefully on lap showcasing bracelets and bangles (face partially shown / lower torso frame)",
    cameraFraming: "Lower torso camera framing with hands resting gracefully on lap showcasing wristwear (face partially shown / lower torso frame)",
    faceVisibilityRule: "partial_face",
    displayOrder: 32,
    isActive: true,
  },
  {
    id: "wrist_cross_arms",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Crossed Arms Wrist Angle",
    nameTe: "చేతులు కట్టుకున్న మణికట్టు యాంగిల్",
    promptDirective: "in a crossed arms posture highlighting wrist accessories over sleeves (face fully or partially shown in confident pose)",
    cameraFraming: "Mid-shot framing crossed arms showcasing wrist accessories over apparel sleeves (face fully or partially shown in confident pose)",
    faceVisibilityRule: "full_face",
    displayOrder: 33,
    isActive: true,
  },
  {
    id: "wrist_hand_chest",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Hand Placed Near Chest",
    nameTe: "ఛాతీ దగ్గర చేయి ఆనించిన భంగిమ",
    promptDirective: "with hand placed near chest/collarbone bringing wrist and rings near neckline (face fully shown with hand touching chest)",
    cameraFraming: "Upper chest framing bringing manicured wrist and rings near neckline (face fully shown with hand touching chest)",
    faceVisibilityRule: "full_face",
    displayOrder: 34,
    isActive: true,
  },
  {
    id: "wrist_side_arm",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Side Arm Extension",
    nameTe: "పక్క చేయి చాచిన భంగిమ",
    promptDirective: "in a side arm extension highlighting watch dial or bangle stack (face partially shown / focused on forearm and wrist)",
    cameraFraming: "Side arm extension close-up focusing on forearm, wrist stack, and bangles (face partially shown / focused on forearm and wrist)",
    faceVisibilityRule: "partial_face",
    displayOrder: 35,
    isActive: true,
  },
  {
    id: "wrist_gesture",
    type: "pose",
    workspace: "jewelry",
    subCategory: "wrist_ring",
    nameEn: "Fluid Hand Gesture",
    nameTe: "చేతి సున్నితమైన కదలిక",
    promptDirective: "in a fluid hand gesture in mid-motion showcasing sparkling wristwear (face fully or partially shown in background)",
    cameraFraming: "Mid-motion hand gesture framing wristwear against soft studio background (face fully or partially shown in background)",
    faceVisibilityRule: "partial_face",
    displayOrder: 36,
    isActive: true,
  },

  // ==========================================
  // 7. JEWELRY POSES (Hip & Waist)
  // ==========================================
  {
    id: "hip_waist_mid",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Midsection Waist Focus",
    nameTe: "నడుము మధ్య భాగం ఫోకస్",
    promptDirective: "in a midsection waist focus framing waistline ornament over ethnic drapes (face partially shown — cropped near lower ribs or chin, prioritizing waistline)",
    cameraFraming: "Midsection waist close-up framing hip chain or kamarbandh over apparel drapes (face partially shown — cropped near lower ribs or chin, prioritizing waistline)",
    faceVisibilityRule: "partial_face",
    displayOrder: 37,
    isActive: true,
  },
  {
    id: "hip_hands_on_waist",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Hands-on-Waist 3/4 Pose",
    nameTe: "నడుముపై చేతులు ఉంచిన 3/4 భంగిమ",
    promptDirective: "with hands on waist in three-quarter pose framing hip chain (face fully or partially shown)",
    cameraFraming: "Hands-on-waist three-quarter shot framing waistline ornament and hip curve (face fully or partially shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 38,
    isActive: true,
  },
  {
    id: "hip_royal_standing",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Regal Standing Waistline",
    nameTe: "రాయల్ నిలబడే నడుము పట్టి వ్యూ",
    promptDirective: "in a regal standing posture showcasing full waistline and lower apparel (face fully shown with tall posture)",
    cameraFraming: "Tall standing posture framing full waistline and royal hip ornament (face fully shown with tall posture)",
    faceVisibilityRule: "full_face",
    displayOrder: 39,
    isActive: true,
  },
  {
    id: "hip_side_turn",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Side Hip Curve Angle",
    nameTe: "పక్క నడుము మలుపు యాంగిల్",
    promptDirective: "in a side hip curve angle accentuating waist belt drapes (face partially or fully shown in side angle)",
    cameraFraming: "Side hip curve angle accentuating waist belt drapes and side clasp (face partially or fully shown in side angle)",
    faceVisibilityRule: "partial_face",
    displayOrder: 40,
    isActive: true,
  },
  {
    id: "hip_saree_drape",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Saree Draped Waistline",
    nameTe: "చీర డ్రేప్‌లో నడుము పట్టి వ్యూ",
    promptDirective: "in a saree draped waistline shot focusing on central motif (face fully or partially shown)",
    cameraFraming: "Traditional saree drape shot centering waistband motif against pleated silk (face fully or partially shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 41,
    isActive: true,
  },
  {
    id: "hip_front_direct",
    type: "pose",
    workspace: "jewelry",
    subCategory: "hip",
    nameEn: "Direct Frontal Midsection",
    nameTe: "నేరుగా నడుము మధ్య భాగం",
    promptDirective: "in a direct frontal midsection alignment centering hip ornament (face partially shown / lower torso focus)",
    cameraFraming: "Direct frontal midsection alignment highlighting symmetrical waist ornament (face partially shown / lower torso focus)",
    faceVisibilityRule: "partial_face",
    displayOrder: 42,
    isActive: true,
  },

  // ==========================================
  // 8. JEWELRY POSES (Nose)
  // ==========================================
  {
    id: "nose_close_profile",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "Nostril Profile Focus",
    nameTe: "ముక్కు ప్రొఫైల్ ఫోకస్",
    promptDirective: "in a nostril profile focus close-up highlighting delicate nath loop and pearl drop (face partially shown — close macro focus on nose, lips, and cheek)",
    cameraFraming: "Macro nostril profile camera shot highlighting delicate nath loop and pearl drop (face partially shown — close macro focus on nose, lips, and cheek)",
    faceVisibilityRule: "partial_face",
    displayOrder: 43,
    isActive: true,
  },
  {
    id: "nose_front_portrait",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "Direct Facial Portrait",
    nameTe: "నేరుగా ముఖ పోర్ట్రెయిట్",
    promptDirective: "in a direct frontal facial beauty portrait framing nose ring and lips (face fully shown in direct symmetry)",
    cameraFraming: "Direct frontal beauty portrait framing nose ring and lips in high fashion symmetry (face fully shown in direct symmetry)",
    faceVisibilityRule: "full_face",
    displayOrder: 44,
    isActive: true,
  },
  {
    id: "nose_3q_headturn",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "3/4 Head Turn Angle",
    nameTe: "3/4 తల తిరిగిన నాథ్ యాంగిల్",
    promptDirective: "in a three-quarter head turn capturing nath chain connecting to hair (face fully shown in 3/4 turn)",
    cameraFraming: "Three-quarter head turn angle capturing nath chain connecting to hair (face fully shown in 3/4 turn)",
    faceVisibilityRule: "full_face",
    displayOrder: 45,
    isActive: true,
  },
  {
    id: "nose_bridal_veil",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "Bridal Veil Side Angle",
    nameTe: "పెళ్ళికూతురు ముసుగు సైడ్ యాంగిల్",
    promptDirective: "in a bridal veil side angle with sheer dupatta framing nose ring and eyes (face partially shown / softly veiled)",
    cameraFraming: "Bridal veil side angle with sheer dupatta framing nose ring, eyes, and cheek (face partially shown / softly veiled)",
    faceVisibilityRule: "partial_face",
    displayOrder: 46,
    isActive: true,
  },
  {
    id: "nose_soft_smile",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "Subtle Smile Close-Up",
    nameTe: "చిరునవ్వుతో ముక్కు పుడక షాట్",
    promptDirective: "in a subtle smile close-up accentuating nose pin shimmer near lips (face fully shown with gentle expression)",
    cameraFraming: "Subtle smile close-up accentuating nose pin shimmer near lips (face fully shown with gentle expression)",
    faceVisibilityRule: "full_face",
    displayOrder: 47,
    isActive: true,
  },
  {
    id: "nose_macro_focus",
    type: "pose",
    workspace: "jewelry",
    subCategory: "nose",
    nameEn: "Ultra Macro Nosepin",
    nameTe: "అల్ట్రా మాక్రో ముక్కు పుడక",
    promptDirective: "in an ultra macro nosepin focus centering the nose ornament (face partially shown — tight macro crop on nose and cheek)",
    cameraFraming: "Ultra macro beauty close-up centering the nose ornament and skin texture (face partially shown — tight macro crop on nose and cheek)",
    faceVisibilityRule: "partial_face",
    displayOrder: 48,
    isActive: true,
  },

  // ==========================================
  // 9. JEWELRY POSES (Finger & Hand)
  // ==========================================
  {
    id: "finger_hand_gesture",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Hand & Finger Close-Up",
    nameTe: "చేతి వేళ్ళు & ఉంగరం క్లోజ్-అప్",
    promptDirective: "in a hand and finger close-up gesture displaying rings on manicured fingers (face partially shown — softly blurred or cropped above chest)",
    cameraFraming: "Close-up hand gesture shot displaying rings on manicured fingers (face partially shown — softly blurred or cropped above chest)",
    faceVisibilityRule: "partial_face",
    displayOrder: 49,
    isActive: true,
  },
  {
    id: "finger_chin_rest",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Hand Resting on Chin",
    nameTe: "గడ్డం కింద చేయి ఆనించిన భంగిమ",
    promptDirective: "with hand softly resting on chin/cheek highlighting ring on finger near lips (face fully shown with hand touching chin)",
    cameraFraming: "Beauty close-up with hand resting softly near chin/cheek, framing finger ring near facial features (face fully shown with hand touching chin)",
    faceVisibilityRule: "full_face",
    displayOrder: 50,
    isActive: true,
  },
  {
    id: "finger_hands_clasped",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Hands Clasped Together",
    nameTe: "చేతులు కలిపిన ఉంగరాల షాట్",
    promptDirective: "with hands clasped together in front of chest showcasing multiple rings (face fully or partially shown)",
    cameraFraming: "Mid-shot framing clasped hands in front of chest showcasing multiple rings (face fully or partially shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 51,
    isActive: true,
  },
  {
    id: "finger_holding_prop",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Delicate Hand Pose",
    nameTe: "సున్నితమైన చేతి ఉంగరం భంగిమ",
    promptDirective: "in a delicate hand pose holding silk fabric showcasing ring facets (face partially shown / focus on hand and ring)",
    cameraFraming: "Close-up hand framing holding silk fabric showcasing ring facets (face partially shown / focus on hand and ring)",
    faceVisibilityRule: "partial_face",
    displayOrder: 52,
    isActive: true,
  },
  {
    id: "finger_macro_ring",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Macro Ring Diamond Focus",
    nameTe: "ఉంగరం డైమండ్ ఫోకస్",
    promptDirective: "in a macro focus on solitaire diamond ring on finger (face partially shown / macro focus on hand)",
    cameraFraming: "Ultra macro focus centering solitaire diamond ring on finger (face partially shown / macro focus on hand)",
    faceVisibilityRule: "partial_face",
    displayOrder: 53,
    isActive: true,
  },
  {
    id: "finger_side_hand",
    type: "pose",
    workspace: "jewelry",
    subCategory: "finger",
    nameEn: "Side Profile Hand Placement",
    nameTe: "పక్క చేయి ఆనించిన భంగిమ",
    promptDirective: "in a side profile hand placement highlighting ring band detail (face partially shown / focus on hand profile)",
    cameraFraming: "Side profile hand placement highlighting ring band and setting depth (face partially shown / focus on hand profile)",
    faceVisibilityRule: "partial_face",
    displayOrder: 54,
    isActive: true,
  },

  // ==========================================
  // 10. JEWELRY POSES (Leg & Anklets / Payal)
  // ==========================================
  {
    id: "anklet_floor_cross_legged",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Cross-Legged Floor Pose",
    nameTe: "నేలపై క్రాస్-లెగ్డ్ కూర్చున్న భంగిమ",
    promptDirective: "seated cross-legged on a polished wooden/marbled floor, with legs neatly folded displaying payal drapes and toe ring details (lower body / feet close-up focus)",
    cameraFraming: "Seated cross-legged posture on smooth floor/carpet framing ankles, payal, and toe rings gracefully (lower body/feet focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 55,
    isActive: true,
  },
  {
    id: "anklet_floor_legs_extended",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Floor Seated Legs Extended",
    nameTe: "నేలపై కాళ్ళు చాపి కూర్చున్న భంగిమ",
    promptDirective: "sitting gracefully on the floor with legs extended forward, displaying shimmering anklet chains and intricate toe rings resting gently on smooth floor (feet and lower leg focus)",
    cameraFraming: "Seated floor posture with legs extended forward, ankles and feet resting side by side highlighting payal and toe rings (lower body focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 56,
    isActive: true,
  },
  {
    id: "anklet_floor_kneeling_mehendi",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Floor Kneeling / Mehendi Pose",
    nameTe: "నేలపై మోకాళ్ళపై మెహందీ భంగిమ",
    promptDirective: "kneeling gracefully on a rich carpeted or marble floor, top-down angle capturing payal chainwork, ghungroo drops, and shimmering toe rings against floor decor",
    cameraFraming: "Kneeling posture on decorative floor/carpet, top-down angle showcasing payal bells, heel drapes, and toe ornaments (lower body focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 57,
    isActive: true,
  },
  {
    id: "anklet_ankle_close",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Lower Leg & Ankle Focus",
    nameTe: "కాలు & పట్టీలు క్లోజ్-అప్",
    promptDirective: "in a lower leg and ankle focus close-up showcasing payal and ghungroo bells (face partially shown — strictly lower leg focus, face cropped out of frame)",
    cameraFraming: "Lower leg macro close-up framing ankle, payal, and ghungroo bells (face partially shown — strictly lower leg focus, face cropped out of frame)",
    faceVisibilityRule: "no_face",
    displayOrder: 58,
    isActive: true,
  },
  {
    id: "anklet_step_forward",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Forward Step Motion",
    nameTe: "అడుగు ముందుకు వేసిన పాయల్ భంగిమ",
    promptDirective: "in a forward step motion highlighting anklet drape on foot (face partially shown — lower body/feet focus, face cropped out)",
    cameraFraming: "Dynamic forward step stride framing anklet drape on foot and heel (face partially shown — lower body/feet focus, face cropped out of frame)",
    faceVisibilityRule: "no_face",
    displayOrder: 59,
    isActive: true,
  },
  {
    id: "anklet_seated_foot",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Seated Foot Display Pose",
    nameTe: "కూర్చుని పట్టీలు చూపే షాట్",
    promptDirective: "in a seated foot display pose with foot resting on cushion (face partially shown — feet and lower leg focus)",
    cameraFraming: "Seated foot framing with foot resting on cushion showcasing anklet links (face partially shown — feet and lower leg focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 60,
    isActive: true,
  },
  {
    id: "anklet_side_foot",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Side Ankle & Heel Angle",
    nameTe: "పక్క మడమ & పట్టీల యాంగిల్",
    promptDirective: "in a side ankle and heel angle showcasing delicate chainwork (face partially shown — foot and ankle focus)",
    cameraFraming: "Side angle heel and ankle profile close-up (face partially shown — foot and ankle focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 61,
    isActive: true,
  },
  {
    id: "anklet_both_feet",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Both Feet Draped Together",
    nameTe: "రెండు కాళ్ళ పట్టీలు కనిపించే షాట్",
    promptDirective: "with both feet draped together displaying pair of payals (face partially shown — feet focus)",
    cameraFraming: "Camera framing both feet draped together displaying pair of payals (face partially shown — feet focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 62,
    isActive: true,
  },
  {
    id: "anklet_toering_focus",
    type: "pose",
    workspace: "jewelry",
    subCategory: "leg",
    nameEn: "Toe Ring & Ankle Focus",
    nameTe: "మెట్టెలు & పట్టీల క్లోజ్-అప్",
    promptDirective: "in a toe ring and ankle focus close-up (face partially shown — feet and toes focus)",
    cameraFraming: "Intimate toe ring and foot arch close-up (face partially shown — feet and toes focus)",
    faceVisibilityRule: "no_face",
    displayOrder: 63,
    isActive: true,
  },

  // ==========================================
  // 11. JEWELRY POSES (Forehead & Head)
  // ==========================================
  {
    id: "forehead_tikka_center",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "Center Forehead Tikka Focus",
    nameTe: "పాపిడి బిళ్ళ క్లోజ్-అప్",
    promptDirective: "in a close-up direct forehead and hairline beauty shot, highlighting center-placed maang tikka or borla (face fully shown — centered on upper face, eyes, and forehead)",
    cameraFraming: "Close-up forehead and hairline camera angle centering maang tikka or borla (face fully shown — centered on upper face, eyes, and forehead)",
    faceVisibilityRule: "full_face",
    displayOrder: 64,
    isActive: true,
  },
  {
    id: "forehead_mathapatti_frame",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "Full Hairline Matha Patti",
    nameTe: "మాతా పట్టీ పూర్తి హెయిర్‌లైన్ షాట్",
    promptDirective: "in a frontal beauty portrait framing full forehead and hairline, displaying elaborate Kundan matha patti craftsmanship (face fully shown in frontal beauty portrait)",
    cameraFraming: "Frontal beauty portrait framing full forehead and hairline with matha patti (face fully shown in frontal beauty portrait)",
    faceVisibilityRule: "full_face",
    displayOrder: 65,
    isActive: true,
  },
  {
    id: "forehead_3q_headturn",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "3/4 Head Turn Angle",
    nameTe: "3/4 తల తిరిగిన అలంకరణ భంగిమ",
    promptDirective: "in a three-quarter head turn angle showcasing forehead ornament, temple detailing, and facial contouring (face fully shown in 3/4 angle)",
    cameraFraming: "Three-quarter head turn angle showcasing forehead ornament and temple detailing (face fully shown in 3/4 angle)",
    faceVisibilityRule: "full_face",
    displayOrder: 66,
    isActive: true,
  },
  {
    id: "forehead_bridal_veil",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "Bridal Dupatta / Veil Frame",
    nameTe: "పెళ్ళికూతురు ముసుగు హెడ్‌పీస్ యాంగిల్",
    promptDirective: "in a side angle bridal portrait with sheer dupatta framing forehead ornament and eyes (face partially shown / veiled face with eyes and forehead clear)",
    cameraFraming: "Side angle bridal portrait with sheer dupatta framing forehead ornament and eyes (face partially shown / veiled face with eyes and forehead clear)",
    faceVisibilityRule: "partial_face",
    displayOrder: 67,
    isActive: true,
  },
  {
    id: "forehead_side_passa",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "Side Temple Passa Focus",
    nameTe: "సైడ్ ఝుమర్ / పస్సా ప్రొఫైల్",
    promptDirective: "in a side profile head angle highlighting passa / jhumar draped gracefully over temple and hair (face partially shown in side profile focusing on temple and hair)",
    cameraFraming: "Side profile head angle highlighting passa / jhumar draped over temple and hair (face partially shown in side profile focusing on temple and hair)",
    faceVisibilityRule: "partial_face",
    displayOrder: 68,
    isActive: true,
  },
  {
    id: "forehead_front_portrait",
    type: "pose",
    workspace: "jewelry",
    subCategory: "forehead",
    nameEn: "Direct Forehead Beauty Portrait",
    nameTe: "నేరుగా పాపిడి అలంకరణ పోర్ట్రెయిట్",
    promptDirective: "in a symmetrical front-facing beauty portrait centering forehead jewelry, eyes, and regal poise (face fully shown in regal symmetry)",
    cameraFraming: "Direct front-facing beauty portrait centering forehead jewelry, eyes, and regal poise (face fully shown in regal symmetry)",
    faceVisibilityRule: "full_face",
    displayOrder: 69,
    isActive: true,
  },

  // ==========================================
  // 12. CLASSIC & ACCESORY POSES
  // ==========================================
  {
    id: "hand_face_gesture",
    type: "pose",
    workspace: "jewelry",
    subCategory: "accessories",
    nameEn: "Hand-to-Face Gesture",
    nameTe: "చేతితో ముఖం తాకే భంగిమ",
    promptDirective: "in a graceful beauty pose with manicured hand and fingers softly resting near the cheek or chin (face fully shown in beauty portrait)",
    cameraFraming: "Hand-to-face beauty gesture shot, manicured fingers touching cheek/chin, framing rings and bracelets alongside facial poise (face fully shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 70,
    isActive: true,
  },
  {
    id: "three_quarter_gaze",
    type: "pose",
    workspace: "jewelry",
    subCategory: "accessories",
    nameEn: "Three-Quarter Elegance",
    nameTe: "మూడు వంతుల ముఖచిత్రం",
    promptDirective: "in a classic three-quarter high-fashion beauty portrait with a subtle head tilt and serene gaze (face fully shown in 3/4 high-fashion gaze)",
    cameraFraming: "Three-quarter elegance portrait, subtle head tilt and studio gaze, capturing harmonized necklace and earring brilliance (face fully shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 71,
    isActive: true,
  },
  {
    id: "front_direct_portrait",
    type: "pose",
    workspace: "jewelry",
    subCategory: "accessories",
    nameEn: "Direct Frontal Portrait",
    nameTe: "నేరుగా నిలువు ముఖచిత్రం",
    promptDirective: "in a regal direct-facing portrait looking into the camera with poised confidence (face fully shown looking directly into camera)",
    cameraFraming: "Direct frontal close-up beauty portrait, framing face, neckline, and shoulders with high-fashion symmetry (face fully shown)",
    faceVisibilityRule: "full_face",
    displayOrder: 72,
    isActive: true,
  }
];
