/**
 * Seed data for all Garment and Jewelry Background Environments
 */

export interface SeedBackground {
  id: string;
  type: "background";
  workspace: "garment" | "jewelry" | "all";
  subCategory: "indoor" | "outdoor";
  nameEn: string;
  nameTe: string;
  promptDirective: string;
  colorHex?: string;
  displayOrder: number;
  isActive: boolean;
}

export const SEED_BACKGROUNDS: SeedBackground[] = [
  {
    id: "plain",
    type: "background",
    workspace: "all",
    subCategory: "indoor",
    nameEn: "Plain Studio Backdrop",
    nameTe: "సాదా రంగు (Plain Color)",
    promptDirective: "against a clean seamless minimalist solid plain studio background with soft natural drop shadow",
    colorHex: "#fdfbf7",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "studio",
    type: "background",
    workspace: "all",
    subCategory: "indoor",
    nameEn: "Studio Lighting",
    nameTe: "స్టూడియో లైటింగ్",
    promptDirective: "in a high-end luxury fashion photography studio, professional softbox three-point lighting, subtle shadows, professional editorial style",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "traditional",
    type: "background",
    workspace: "all",
    subCategory: "outdoor",
    nameEn: "Indian Heritage Courtyard",
    nameTe: "భారతీయ సాంప్రదాయం",
    promptDirective: "inside an elegant, beautifully lit rich Indian courtyard, traditional arch design, warm light, premium ethnic background",
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "festival",
    type: "background",
    workspace: "all",
    subCategory: "indoor",
    nameEn: "Festive Lights & Diyas",
    nameTe: "పండుగ / దీపావళి వెలుగులు",
    promptDirective: "decorated for Diwali festival, surrounded by warm glittering bokeh lights, glowing clay oil lamps (diyas), elegant traditional backdrop",
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "luxury",
    type: "background",
    workspace: "all",
    subCategory: "indoor",
    nameEn: "Italian Marble Floor",
    nameTe: "లగ్జరీ మార్బుల్ నేల",
    promptDirective: "on a magnificent polished Italian white marble floor with luxurious golden accents and elegant reflection",
    displayOrder: 5,
    isActive: true,
  },
  {
    id: "royal",
    type: "background",
    workspace: "all",
    subCategory: "outdoor",
    nameEn: "Royal Palace Balcony",
    nameTe: "రాజభవనం",
    promptDirective: "in front of an ornate royal palace balcony at sunset, soft warm golden hour light, majestic heritage Indian setting",
    displayOrder: 6,
    isActive: true,
  },
  {
    id: "wood",
    type: "background",
    workspace: "jewelry",
    subCategory: "indoor",
    nameEn: "Solid Teak Wood",
    nameTe: "చెక్క బల్ల",
    promptDirective: "placed beautifully on a rustic dark polished solid teak wood table, with soft warm side-lighting, organic and premium feel",
    displayOrder: 7,
    isActive: true,
  },
  {
    id: "beach",
    type: "background",
    workspace: "jewelry",
    subCategory: "outdoor",
    nameEn: "Fine Golden Sand",
    nameTe: "బీచ్ వాతావరణం",
    promptDirective: "placed on fine golden sand in a photographic frame composition of sand, warm coastal sunlight",
    displayOrder: 8,
    isActive: true,
  },
  {
    id: "velvet",
    type: "background",
    workspace: "jewelry",
    subCategory: "indoor",
    nameEn: "Deep Crimson Velvet",
    nameTe: "వెల్వెట్ బ్యాక్‌గ్రౌండ్",
    promptDirective: "nestled inside a luxurious deep-crimson velvet textile fabric background, creating beautiful contrast and high-fashion editorial aura",
    displayOrder: 9,
    isActive: true,
  },
  {
    id: "silk",
    type: "background",
    workspace: "jewelry",
    subCategory: "indoor",
    nameEn: "Pure Royal Blue Silk",
    nameTe: "పట్టు వస్త్రం (సిల్క్)",
    promptDirective: "resting gracefully on a drape of pure royal-blue silk saree cloth, reflecting soft warm light and magnificent texture",
    displayOrder: 10,
    isActive: true,
  },
  {
    id: "granite",
    type: "background",
    workspace: "jewelry",
    subCategory: "indoor",
    nameEn: "Polished Black Granite",
    nameTe: "గ్రానైట్ నేల",
    promptDirective: "placed elegantly on a slab of rough-textured polished black granite stone, with architectural side spotlight shadows",
    displayOrder: 11,
    isActive: true,
  },
  {
    id: "mirror",
    type: "background",
    workspace: "jewelry",
    subCategory: "indoor",
    nameEn: "Dark Reflective Mirror",
    nameTe: "అద్దం ప్రతిబింబం",
    promptDirective: "placed on a polished dark reflective mirror plate, capturing a flawless symmetric luxury reflection under dim atmospheric warm lighting",
    displayOrder: 12,
    isActive: true,
  },
  {
    id: "urban",
    type: "background",
    workspace: "garment",
    subCategory: "outdoor",
    nameEn: "Downtown Urban Brick Wall",
    nameTe: "నగర వీధి (అర్బన్)",
    promptDirective: "against a fashionable chic downtown urban brick wall background with modern street cafe vibe, soft natural daylight",
    displayOrder: 13,
    isActive: true,
  },
  {
    id: "vintage",
    type: "background",
    workspace: "garment",
    subCategory: "indoor",
    nameEn: "Vintage Palace Room",
    nameTe: "పాతకాలపు గది (వింటేజ్)",
    promptDirective: "inside a magnificent vintage Indian palace room, featuring hand-carved heritage arches, antique royal wooden columns, vintage brass chandeliers, and soft atmospheric golden light filtering through ornamental windows",
    displayOrder: 14,
    isActive: true,
  },
  {
    id: "modern_office",
    type: "background",
    workspace: "garment",
    subCategory: "indoor",
    nameEn: "Modern Architectural Office",
    nameTe: "ఆధునిక ఆఫీస్",
    promptDirective: "inside a clean high-end architectural corporate office space with large windows and a beautiful city skyline background",
    displayOrder: 15,
    isActive: true,
  }
];
