/**
 * Seed data for all 72 human model faces across 6 ethnicities and 2 genders
 */

export interface SeedFace {
  id: string;
  type: "face";
  workspace: "all";
  subCategory: "indian" | "african" | "asian" | "western" | "mideast" | "latina";
  nameEn: string;
  nameTe: string;
  promptDirective: string;
  previewImageUrl: string;
  storagePath: string;
  metadata: {
    gender: "female" | "male";
    ethnicity: string;
    category: string;
  };
  displayOrder: number;
  isActive: boolean;
}

const SUPABASE_CDN_BASE = "https://xfooqaqjeaqcoddihphl.supabase.co/storage/v1/object/public/model-faces";

export const SEED_FACES: SeedFace[] = [
  // --- INDIAN FEMALE (6 Faces) ---
  {
    id: "indian_f",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Ananya",
    nameTe: "అనన్య",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a beautiful Indian female model with a soft, warm commercial smile, bright expressive dark eyes, glowing smooth skin, looking directly at the camera, solid neutral light studio background, face fully visible with no hair or accessories covering facial features",
    previewImageUrl: `${SUPABASE_CDN_BASE}/ananya.jpg`,
    storagePath: "model-faces/ananya.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "indian_f2",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Priya",
    nameTe: "ప్రియా",
    promptDirective: "a professional, ultra-high-resolution studio portrait headshot of an elegant South Indian female model with regal features, soft natural expression, radiant complexion, looking directly at camera with clear eye contact, neutral clean background, face unobscured",
    previewImageUrl: `${SUPABASE_CDN_BASE}/priya.jpg`,
    storagePath: "model-faces/priya.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "editorial_f",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Meera",
    nameTe: "మీరా",
    promptDirective: "an ultra-high-resolution close-up high-fashion editorial studio portrait of a striking Indian female model with intense gaze, razor-sharp jawline, glowing flawless skin, elegant facial symmetry, soft studio rim light, minimalist grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/meera.jpg`,
    storagePath: "model-faces/meera.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "indian_f4",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Kavya",
    nameTe: "కావ్య",
    promptDirective: "a professional ultra-high-resolution close-up studio headshot of a charming North Indian female model with gentle smile, expressive eyes, warm skin tone, clean studio backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/kavya.jpg`,
    storagePath: "model-faces/kavya.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "indian_f5",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Diya",
    nameTe: "దియా",
    promptDirective: "a studio portrait of a glamorous Indian female fashion model with radiant smile, glossy hair, flawless complexion, professional rim lighting, neutral studio background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/diya.jpg`,
    storagePath: "model-faces/diya.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 5,
    isActive: true,
  },
  {
    id: "indian_f6",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Pooja",
    nameTe: "పూజ",
    promptDirective: "a close-up headshot of a confident modern Indian female model, soft natural studio lighting, direct eye contact, clean solid backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/pooja.jpg`,
    storagePath: "model-faces/pooja.jpg",
    metadata: { gender: "female", ethnicity: "indian", category: "indian" },
    displayOrder: 6,
    isActive: true,
  },

  // --- INDIAN MALE (6 Faces) ---
  {
    id: "indian_m",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Rohan",
    nameTe: "రోహన్",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a handsome Indian male model, looking directly at the camera with a confident, friendly expression, neatly groomed stubble, sharp features, even studio lighting, solid neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/rohan.jpg`,
    storagePath: "model-faces/rohan.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 7,
    isActive: true,
  },
  {
    id: "indian_m2",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Arjun",
    nameTe: "అర్జున్",
    promptDirective: "a professional, ultra-high-resolution studio headshot of a charming South Asian male model, clear eye contact, gentle confident expression, sharp jawline, clean professional lighting, solid grey studio background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/arjun.jpg`,
    storagePath: "model-faces/arjun.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 8,
    isActive: true,
  },
  {
    id: "editorial_m",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Vikram",
    nameTe: "విక్రమ్",
    promptDirective: "an ultra-high-resolution close-up studio headshot of a sharp male fashion model, sculpted jawline, intense focused gaze, subtle beard, crisp lighting contrast, high-end commercial model portfolio photo",
    previewImageUrl: `${SUPABASE_CDN_BASE}/vikram.jpg`,
    storagePath: "model-faces/vikram.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 9,
    isActive: true,
  },
  {
    id: "indian_m4",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Aaditya",
    nameTe: "ఆదిత్య",
    promptDirective: "a studio headshot of a handsome young Indian male model with well-defined jawline, confident warm smile, studio softbox lighting, clean grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/aaditya.jpg`,
    storagePath: "model-faces/aaditya.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 10,
    isActive: true,
  },
  {
    id: "indian_m5",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Kabir",
    nameTe: "కబీర్",
    promptDirective: "a close-up portrait of an attractive South Indian male model, groomed facial hair, warm expression, direct gaze, neutral studio setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/kabir.jpg`,
    storagePath: "model-faces/kabir.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 11,
    isActive: true,
  },
  {
    id: "indian_m6",
    type: "face",
    workspace: "all",
    subCategory: "indian",
    nameEn: "Suresh",
    nameTe: "సురేష్",
    promptDirective: "a commercial portrait headshot of a South Indian male model with charismatic smile, sharp clear features, studio portrait illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/suresh.jpg`,
    storagePath: "model-faces/suresh.jpg",
    metadata: { gender: "male", ethnicity: "indian", category: "indian" },
    displayOrder: 12,
    isActive: true,
  },

  // --- AFRICAN FEMALE (6 Faces) ---
  {
    id: "african_f",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Amara",
    nameTe: "అమరా",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a stunning African female model with smooth clear dark skin, radiant warm smile, sharp high cheekbones, looking directly at camera, soft studio lighting, clean background, face unobscured",
    previewImageUrl: `${SUPABASE_CDN_BASE}/amara.jpg`,
    storagePath: "model-faces/amara.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 13,
    isActive: true,
  },
  {
    id: "african_f2",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Zuri",
    nameTe: "జూరి",
    promptDirective: "an editorial fashion studio portrait of a regal African female model with glowing melanin skin, intense expressive eyes, elegant posture, soft key lighting, minimal grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/zuri.jpg`,
    storagePath: "model-faces/zuri.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 14,
    isActive: true,
  },
  {
    id: "african_f3",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Nia",
    nameTe: "నియా",
    promptDirective: "a close-up studio portrait of a beautiful West African female model with natural smile, flawless dark skin tone, clear gaze, balanced key light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/nia.jpg`,
    storagePath: "model-faces/nia.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 15,
    isActive: true,
  },
  {
    id: "african_f4",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Aaliyah",
    nameTe: "ఆలియా",
    promptDirective: "a high-resolution studio face portrait of a glamorous African female model, bright confident eyes, smooth skin tone, professional studio flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/aaliyah.jpg`,
    storagePath: "model-faces/aaliyah.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 16,
    isActive: true,
  },
  {
    id: "african_f5",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Fatoumata",
    nameTe: "ఫాతుమాతా",
    promptDirective: "a studio headshot of an African fashion model with vibrant smile, delicate features, clean neutral backdrop, soft studio fill",
    previewImageUrl: `${SUPABASE_CDN_BASE}/fatoumata.jpg`,
    storagePath: "model-faces/fatoumata.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 17,
    isActive: true,
  },
  {
    id: "african_f6",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Binta",
    nameTe: "బింటా",
    promptDirective: "a close-up commercial studio face shot of an East African female model with warm smile, radiant skin, looking straight into lens",
    previewImageUrl: `${SUPABASE_CDN_BASE}/binta.jpg`,
    storagePath: "model-faces/binta.jpg",
    metadata: { gender: "female", ethnicity: "african", category: "african" },
    displayOrder: 18,
    isActive: true,
  },

  // --- AFRICAN MALE (6 Faces) ---
  {
    id: "african_m",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Kwame",
    nameTe: "క్వామే",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a handsome African male model, looking directly at camera with a warm confident expression, smooth dark skin, sharp features, even studio lighting, solid neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/kwame.jpg`,
    storagePath: "model-faces/kwame.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 19,
    isActive: true,
  },
  {
    id: "african_m2",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Malik",
    nameTe: "మాలిక్",
    promptDirective: "an editorial fashion studio headshot of a handsome African male model with sculpted jawline, intense eyes, subtle stubble, clean studio rim light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/malik.jpg`,
    storagePath: "model-faces/malik.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 20,
    isActive: true,
  },
  {
    id: "african_m3",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Zain",
    nameTe: "జైన్",
    promptDirective: "a close-up portrait shot of an attractive Black male model with friendly smile, warm dark skin tone, direct gaze, solid grey studio setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/zain.jpg`,
    storagePath: "model-faces/zain.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 21,
    isActive: true,
  },
  {
    id: "african_m4",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Tariq_af",
    nameTe: "తారిఖ్",
    promptDirective: "a studio commercial headshot of a Black male model with confident expression, clean shave, sharp facial symmetry, professional key light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/tariq_af.jpg`,
    storagePath: "model-faces/tariq_af.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 22,
    isActive: true,
  },
  {
    id: "african_m5",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Kofi",
    nameTe: "కోఫీ",
    promptDirective: "a close-up portrait of an African male fashion model, charming smile, sharp cheekbones, studio illumination, clean neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/kofi.jpg`,
    storagePath: "model-faces/kofi.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 23,
    isActive: true,
  },
  {
    id: "african_m6",
    type: "face",
    workspace: "all",
    subCategory: "african",
    nameEn: "Oumar",
    nameTe: "ఒమర్",
    promptDirective: "a studio headshot of a strong Black male model with focused gaze, clean facial features, soft directional key lighting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/oumar.jpg`,
    storagePath: "model-faces/oumar.jpg",
    metadata: { gender: "male", ethnicity: "african", category: "african" },
    displayOrder: 24,
    isActive: true,
  },

  // --- EAST ASIAN FEMALE (6 Faces) ---
  {
    id: "korean_f",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Soo-Jin",
    nameTe: "సూ-జిన్",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Korean female model with flawless glass skin, looking directly at camera with a polite soft smile, sharp clean features, even studio lighting, solid light neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/soojin.jpg`,
    storagePath: "model-faces/soojin.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 25,
    isActive: true,
  },
  {
    id: "asian_f2",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Mei-Ling",
    nameTe: "మేయ్-లింగ్",
    promptDirective: "an editorial studio portrait of a Chinese female fashion model with razor-sharp cheekbones, intense gaze, flawless Porcelain complexion, minimal backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/meiling.jpg`,
    storagePath: "model-faces/meiling.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 26,
    isActive: true,
  },
  {
    id: "asian_f3",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Yoko",
    nameTe: "యోకో",
    promptDirective: "a studio face portrait of a Japanese female model with gentle serene smile, smooth skin, clear dark eyes, soft studio illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/yoko.jpg`,
    storagePath: "model-faces/yoko.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 27,
    isActive: true,
  },
  {
    id: "asian_f4",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Linh",
    nameTe: "లిన్",
    promptDirective: "a close-up studio headshot of a Vietnamese female model with radiant complexion, confident open smile, softbox lighting, clean grey setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/linh.jpg`,
    storagePath: "model-faces/linh.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 28,
    isActive: true,
  },
  {
    id: "asian_f5",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Ji-Eun",
    nameTe: "జి-ఇయున్",
    promptDirective: "a commercial face shot of a young East Asian female model with luminous skin, subtle makeup, direct camera contact, even studio light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/jieun.jpg`,
    storagePath: "model-faces/jieun.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 29,
    isActive: true,
  },
  {
    id: "asian_f6",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Chen",
    nameTe: "చెన్",
    promptDirective: "a high-fashion close-up headshot of an East Asian model with delicate features, elegant pose, clean studio key illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/chen.jpg`,
    storagePath: "model-faces/chen.jpg",
    metadata: { gender: "female", ethnicity: "asian", category: "asian" },
    displayOrder: 30,
    isActive: true,
  },

  // --- EAST ASIAN MALE (6 Faces) ---
  {
    id: "korean_m",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Min-Ho",
    nameTe: "మిన్-హో",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a handsome Korean male model, looking directly at camera with a clean confident expression, sharp features, even studio lighting, solid neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/minho.jpg`,
    storagePath: "model-faces/minho.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 31,
    isActive: true,
  },
  {
    id: "asian_m2",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Kenji",
    nameTe: "కెంజి",
    promptDirective: "an editorial fashion studio headshot of a Japanese male model with sharp jawline, stylish hairstyle, focused gaze, subtle rim lighting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/kenji.jpg`,
    storagePath: "model-faces/kenji.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 32,
    isActive: true,
  },
  {
    id: "asian_m3",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Wei",
    nameTe: "వేయ్",
    promptDirective: "a studio face portrait of a handsome East Asian male model with clear skin, polite confident smile, balanced key studio lighting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/wei.jpg`,
    storagePath: "model-faces/wei.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 33,
    isActive: true,
  },
  {
    id: "asian_m4",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Sang-Woo",
    nameTe: "సాంగ్-వూ",
    promptDirective: "a close-up portrait of a Korean male fashion model with sleek hairstyle, sharp eye contact, minimalist grey studio background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/sangwoo.jpg`,
    storagePath: "model-faces/sangwoo.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 34,
    isActive: true,
  },
  {
    id: "asian_m5",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Hiroshi",
    nameTe: "హిరోషి",
    promptDirective: "a commercial face headshot of an East Asian male model with warm expression, sharp jawline, professional flash illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/hiroshi.jpg`,
    storagePath: "model-faces/hiroshi.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 35,
    isActive: true,
  },
  {
    id: "asian_m6",
    type: "face",
    workspace: "all",
    subCategory: "asian",
    nameEn: "Bao",
    nameTe: "బావో",
    promptDirective: "a close-up studio face photo of a young East Asian male model with clean flawless features, looking directly into lens",
    previewImageUrl: `${SUPABASE_CDN_BASE}/bao.jpg`,
    storagePath: "model-faces/bao.jpg",
    metadata: { gender: "male", ethnicity: "asian", category: "asian" },
    displayOrder: 36,
    isActive: true,
  },

  // --- WESTERN / EU FEMALE (6 Faces) ---
  {
    id: "usa_f",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Sophia",
    nameTe: "సోఫియా",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Caucasian female model with natural friendly expression, bright sharp eyes, soft even commercial lighting, solid light grey background, face fully visible with clear features",
    previewImageUrl: `${SUPABASE_CDN_BASE}/sophia.jpg`,
    storagePath: "model-faces/sophia.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 37,
    isActive: true,
  },
  {
    id: "nordic_f",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Freja",
    nameTe: "ఫ్రెజా",
    promptDirective: "a professional ultra-high-resolution close-up studio headshot of a fair European female model with serene expression, clear blue eyes, delicate features, clean balanced studio light, neutral backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/freja.jpg`,
    storagePath: "model-faces/freja.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 38,
    isActive: true,
  },
  {
    id: "western_f3",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Emma",
    nameTe: "ఎమ్మా",
    promptDirective: "a high-fashion editorial studio headshot of a European female model with radiant blonde hair, bright blue eyes, soft studio illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/emma.jpg`,
    storagePath: "model-faces/emma.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 39,
    isActive: true,
  },
  {
    id: "western_f4",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Charlotte",
    nameTe: "షార్లెట్",
    promptDirective: "a studio commercial portrait of an attractive Western female model with warm smile, hazel eyes, smooth skin tone, clean backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/charlotte.jpg`,
    storagePath: "model-faces/charlotte.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 40,
    isActive: true,
  },
  {
    id: "western_f5",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Chloe",
    nameTe: "క్లోయి",
    promptDirective: "a close-up fashion portrait of a Caucasian female model with sculpted jawline, intense clear gaze, soft directional light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/chloe.jpg`,
    storagePath: "model-faces/chloe.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 41,
    isActive: true,
  },
  {
    id: "western_f6",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Hannah",
    nameTe: "హన్నా",
    promptDirective: "a commercial face shot of a young Western female model with charismatic smile, bright eyes, professional studio flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/hannah.jpg`,
    storagePath: "model-faces/hannah.jpg",
    metadata: { gender: "female", ethnicity: "western", category: "western" },
    displayOrder: 42,
    isActive: true,
  },

  // --- WESTERN / EU MALE (6 Faces) ---
  {
    id: "usa_m",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Ethan",
    nameTe: "ఈథన్",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Caucasian male model, looking directly at camera with a friendly approachable expression, sharp eyes, even professional lighting, solid neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/ethan.jpg`,
    storagePath: "model-faces/ethan.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 43,
    isActive: true,
  },
  {
    id: "nordic_m",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Lucas",
    nameTe: "లూకాస్",
    promptDirective: "a professional ultra-high-resolution close-up studio headshot of a fair European male model, direct gaze into camera, clean natural look, soft studio key light, neutral solid background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/lucas.jpg`,
    storagePath: "model-faces/lucas.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 44,
    isActive: true,
  },
  {
    id: "western_m3",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Alexander",
    nameTe: "అలెక్సాండర్",
    promptDirective: "an editorial fashion studio headshot of a Caucasian male model with strong jawline, blue eyes, groomed hair, clean grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/alexander.jpg`,
    storagePath: "model-faces/alexander.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 45,
    isActive: true,
  },
  {
    id: "western_m4",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Liam",
    nameTe: "లియామ్",
    promptDirective: "a close-up portrait of an attractive Western male model with confident smile, sharp facial features, studio flash lighting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/liam.jpg`,
    storagePath: "model-faces/liam.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 46,
    isActive: true,
  },
  {
    id: "western_m5",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Oliver",
    nameTe: "ఓలివర్",
    promptDirective: "a studio commercial headshot of a European male model with light stubble, focused direct gaze, soft key light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/oliver.jpg`,
    storagePath: "model-faces/oliver.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 47,
    isActive: true,
  },
  {
    id: "western_m6",
    type: "face",
    workspace: "all",
    subCategory: "western",
    nameEn: "Daniel",
    nameTe: "డానియెల్",
    promptDirective: "a close-up studio portrait of a young Caucasian male model with friendly approachable gaze, clear skin, neutral background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/daniel.jpg`,
    storagePath: "model-faces/daniel.jpg",
    metadata: { gender: "male", ethnicity: "western", category: "western" },
    displayOrder: 48,
    isActive: true,
  },

  // --- MIDDLE EAST FEMALE (6 Faces) ---
  {
    id: "mideast_f",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Layla",
    nameTe: "లైలా",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Middle Eastern female model with big dark expressive eyes, warm gentle expression, clear studio lighting, solid background, unobscured face",
    previewImageUrl: `${SUPABASE_CDN_BASE}/layla.jpg`,
    storagePath: "model-faces/layla.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 49,
    isActive: true,
  },
  {
    id: "mideast_f2",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Noor",
    nameTe: "నూర్",
    promptDirective: "an editorial studio portrait of a regal Middle Eastern female model with captivating dark eyes, olive complexion, elegant facial symmetry",
    previewImageUrl: `${SUPABASE_CDN_BASE}/noor.jpg`,
    storagePath: "model-faces/noor.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 50,
    isActive: true,
  },
  {
    id: "mideast_f3",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Yasmin",
    nameTe: "యాస్మిన్",
    promptDirective: "a studio face portrait of a beautiful Arab female model with soft warm smile, expressive dark eyes, flawless smooth skin, studio key light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/yasmin.jpg`,
    storagePath: "model-faces/yasmin.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 51,
    isActive: true,
  },
  {
    id: "mideast_f4",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Farah",
    nameTe: "ఫరా",
    promptDirective: "a close-up studio headshot of a glamorous Middle Eastern female model with luminous complexion, soft rim light, clean grey setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/farah.jpg`,
    storagePath: "model-faces/farah.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 52,
    isActive: true,
  },
  {
    id: "mideast_f5",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Mariam",
    nameTe: "మరియం",
    promptDirective: "a commercial face shot of a young Middle Eastern female model with gentle smile, clear eye contact, studio flash illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/mariam.jpg`,
    storagePath: "model-faces/mariam.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 53,
    isActive: true,
  },
  {
    id: "mideast_f6",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Zeina",
    nameTe: "జైనా",
    promptDirective: "a close-up portrait headshot of an Arab model with striking facial features, elegant posture, balanced studio flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/zeina.jpg`,
    storagePath: "model-faces/zeina.jpg",
    metadata: { gender: "female", ethnicity: "mideast", category: "mideast" },
    displayOrder: 54,
    isActive: true,
  },

  // --- MIDDLE EAST MALE (6 Faces) ---
  {
    id: "mideast_m",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Tariq_me",
    nameTe: "తారిఖ్",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Middle Eastern male model, looking directly at camera with a confident expression, neat beard, sharp eyes, even lighting, solid background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/tariq_me.jpg`,
    storagePath: "model-faces/tariq_me.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 55,
    isActive: true,
  },
  {
    id: "mideast_m2",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Omar",
    nameTe: "ఒమర్",
    promptDirective: "an editorial studio headshot of a handsome Middle Eastern male model with neatly groomed beard, intense gaze, sculpted jawline, grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/omar.jpg`,
    storagePath: "model-faces/omar.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 56,
    isActive: true,
  },
  {
    id: "mideast_m3",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Zayd",
    nameTe: "జైద్",
    promptDirective: "a close-up face portrait of an Arab male fashion model with polite smile, warm skin tone, sharp eye contact, studio setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/zayd.jpg`,
    storagePath: "model-faces/zayd.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 57,
    isActive: true,
  },
  {
    id: "mideast_m4",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Amir",
    nameTe: "అమీర్",
    promptDirective: "a commercial headshot of a Middle Eastern male model with confident pose, groomed facial hair, professional key illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/amir.jpg`,
    storagePath: "model-faces/amir.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 58,
    isActive: true,
  },
  {
    id: "mideast_m5",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Hassan",
    nameTe: "హసన్",
    promptDirective: "a close-up studio headshot of an attractive Middle Eastern male model with charming smile, sharp jawline, directional softbox flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/hassan.jpg`,
    storagePath: "model-faces/hassan.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 59,
    isActive: true,
  },
  {
    id: "mideast_m6",
    type: "face",
    workspace: "all",
    subCategory: "mideast",
    nameEn: "Youssef",
    nameTe: "యూసఫ్",
    promptDirective: "a studio portrait of a young Arab male model with clear skin, natural posture, looking directly into camera lens",
    previewImageUrl: `${SUPABASE_CDN_BASE}/youssef.jpg`,
    storagePath: "model-faces/youssef.jpg",
    metadata: { gender: "male", ethnicity: "mideast", category: "mideast" },
    displayOrder: 60,
    isActive: true,
  },

  // --- LATINA FEMALE (6 Faces) ---
  {
    id: "latina_f",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Isabella",
    nameTe: "ఇసబెల్లా",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Latina female model with warm golden skin tone, confident friendly expression, clear dark eyes, soft studio illumination, clean backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/isabella.jpg`,
    storagePath: "model-faces/isabella.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 61,
    isActive: true,
  },
  {
    id: "latina_f2",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Camila",
    nameTe: "కామిలా",
    promptDirective: "an editorial fashion portrait of a stunning Latina female model with glowing bronzed skin, bright dark eyes, radiant smile, studio flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/camila.jpg`,
    storagePath: "model-faces/camila.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 62,
    isActive: true,
  },
  {
    id: "latina_f3",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Sofia",
    nameTe: "సోఫియా",
    promptDirective: "a close-up studio headshot of a Hispanic female model with razor-sharp cheekbones, intense gaze, smooth complexion, minimal backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/sofia.jpg`,
    storagePath: "model-faces/sofia.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 63,
    isActive: true,
  },
  {
    id: "latina_f4",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Valentina",
    nameTe: "వాలెంటినా",
    promptDirective: "a commercial face shot of a young Latina female model with charismatic smile, golden skin tone, professional softbox illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/valentina.jpg`,
    storagePath: "model-faces/valentina.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 64,
    isActive: true,
  },
  {
    id: "latina_f5",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Elena",
    nameTe: "ఎలెనా",
    promptDirective: "a studio portrait face photo of a Latin American female model with warm friendly expression, clear dark gaze, soft fill light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/elena.jpg`,
    storagePath: "model-faces/elena.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 65,
    isActive: true,
  },
  {
    id: "latina_f6",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Lucia",
    nameTe: "లూసియా",
    promptDirective: "a close-up headshot of a Latina fashion model with delicate facial features, elegant pose, clean studio key light",
    previewImageUrl: `${SUPABASE_CDN_BASE}/lucia.jpg`,
    storagePath: "model-faces/lucia.jpg",
    metadata: { gender: "female", ethnicity: "latina", category: "latina" },
    displayOrder: 66,
    isActive: true,
  },

  // --- LATINO MALE (6 Faces) ---
  {
    id: "latino_m",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Mateo",
    nameTe: "మాటియో",
    promptDirective: "a professional, ultra-high-resolution close-up studio headshot of a Latino male model with warm tan complexion, friendly open smile, sharp clear features, studio lighting, plain background",
    previewImageUrl: `${SUPABASE_CDN_BASE}/mateo.jpg`,
    storagePath: "model-faces/mateo.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 67,
    isActive: true,
  },
  {
    id: "latina_m2",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Santiago",
    nameTe: "సాంటియాగో",
    promptDirective: "an editorial fashion studio headshot of a Latino male model with sculpted jawline, dark hair, confident direct gaze, grey setting",
    previewImageUrl: `${SUPABASE_CDN_BASE}/santiago.jpg`,
    storagePath: "model-faces/santiago.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 68,
    isActive: true,
  },
  {
    id: "latina_m3",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Diego",
    nameTe: "డియాగో",
    promptDirective: "a close-up face portrait of an attractive Hispanic male model with warm open smile, tan skin tone, studio key illumination",
    previewImageUrl: `${SUPABASE_CDN_BASE}/diego.jpg`,
    storagePath: "model-faces/diego.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 69,
    isActive: true,
  },
  {
    id: "latina_m4",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Carlos",
    nameTe: "కార్లోస్",
    promptDirective: "a studio commercial headshot of a Latino male model with light stubble, focused eyes, professional softbox flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/carlos.jpg`,
    storagePath: "model-faces/carlos.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 70,
    isActive: true,
  },
  {
    id: "latina_m5",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Alejandro",
    nameTe: "అలెహాండ్రో",
    promptDirective: "a close-up studio portrait of a young Latino male model with well-defined jawline, charming smile, neutral grey backdrop",
    previewImageUrl: `${SUPABASE_CDN_BASE}/alejandro.jpg`,
    storagePath: "model-faces/alejandro.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 71,
    isActive: true,
  },
  {
    id: "latina_m6",
    type: "face",
    workspace: "all",
    subCategory: "latina",
    nameEn: "Gabriel",
    nameTe: "గాబ్రియెల్",
    promptDirective: "a studio face shot of a Hispanic male model with natural gaze, smooth skin tone, clear directional studio flash",
    previewImageUrl: `${SUPABASE_CDN_BASE}/gabriel.jpg`,
    storagePath: "model-faces/gabriel.jpg",
    metadata: { gender: "male", ethnicity: "latina", category: "latina" },
    displayOrder: 72,
    isActive: true,
  }
];
