export type Language = "en" | "te";

export type Workspace = "garment" | "jewelry" | "billing" | "settings";

export interface AppState {
  language: Language;
  theme: "light" | "dark";
  workspace: Workspace;
  apiKey: string;
  originalImage: string | null; // base64
  removedBgImage: string | null; // base64
  generatedImage: string | null; // base64
  isRemovingBg: boolean;
  isGenerating: boolean;
  generationError: string | null;
  tolerance: number; // for custom bg removal keying
  
  // Garment photographic selections
  garmentType: "saree" | "tshirt" | "jeans" | "shirt" | "western_wear" | "kurta" | "suit" | "salwar" | "lehenga" | "gown" | "skirt" | "crop_top" | "blouse" | "sherwani" | "dhoti" | "blazer" | "tracksuit" | "hoodie";
  garmentPresentation: "model" | "partial_face" | "no_face" | "mannequin" | "hanger" | "ghost" | "flat_lay" | "folded" | "shelf" | "shopwindow";
  garmentModelGender: "female" | "male";
  garmentModelPose: string;
  garmentBackground: "plain" | "studio" | "traditional" | "festival" | "luxury" | "royal" | "urban" | "vintage" | "modern_office";
  garmentBgColor: string; // hex or color name for plain bg

  // Jewelry photographic selections
  jewelryType: "earrings" | "necklace" | "chain" | "ring" | "bracelet" | "watch" | "anklet" | "nose_ring" | "nose" | "noise" | "bangles" | "choker" | "cufflinks" | "pendant" | "kada" | "maang_tikka" | "matha_patti" | "borla" | "passa" | "headband";
  jewelryPresentation: "model" | "bust" | "partial_face" | "no_face";
  jewelryModelGender: "female" | "male";
  jewelryModelPose: string;
  jewelryBustRegion: "head" | "neck" | "wrist" | "ankle" | "finger" | "hand" | "naturally" | "ear";
  jewelryBackground: "plain" | "studio" | "luxury" | "festival" | "traditional" | "wood" | "beach" | "velvet" | "silk" | "granite" | "mirror";
  jewelryBgColor: string;
}

// Full-featured translations for English and Telugu
export const TRANSLATIONS = {
  en: {
    title: "Srushti AI",
    subtitle: "Business to Brand",
    languageToggle: "తెలుగు",
    lightTheme: "Light Mode",
    darkTheme: "Dark Mode",
    
    // Bottom Nav
    navGarment: "Garments",
    navJewelry: "Jewelry",
    navBilling: "Admin Panel",
    navAdmin: "Admin Panel",
    navSettings: "Settings",
    
    // Garment tab labels
    garmentTitle: "Garment Photography",
    garmentSubtitle: "Sarees, T-shirts, Jeans, and more",
    jewelryTitle: "Jewelry Photography",
    jewelrySubtitle: "Necklaces, earrings, and rings",
    billingTitle: "Admin Panel",
    adminTitle: "Admin Panel",
    billingSubtitle: "Configure AI models, pricing, and API keys",
    adminSubtitle: "Configure AI models, pricing, and API keys",
    settingsTitle: "Application Settings",
    settingsSubtitle: "Configure API Key, App Theme, and Language preferences",
    settingsThemeLabel: "Choose Theme / Appearance",
    settingsLanguageLabel: "Choose Language / భాష ఎంచుకోండి",
    
    // Canvas / Upload
    uploadTitle: "Product photo should be a clear front view with all details visible",
    uploadSubtitle: "Drag photo here or tap to capture",
    removingBg: "Removing Background...",
    removeBgSuccess: "Background Removed Successfully!",
    removerTolerance: "Removal Tuning",
    restoreOriginal: "See Original",
    originalLabel: "Original Photo",
    noBgLabel: "Transparent Product",
    finalLabel: "Final AI Photo",
    generating: "Creating Photographic Magic...",
    generateBtn: "Create Photo",
    retryBtn: "Try Again",
    downloadBtn: "Save to Phone",
    shareBtn: "Share Photo",
    
    // Selection Headers
    productType: "Product Type",
    presentationMode: "Presentation Mode",
    useModel: "Put on Human Model?",
    genderLabel: "Model Gender",
    poseLabel: "Model Pose / Camera Angle",
    standing_front: "Standing Front Pose",
    standing_side: "Standing Side Profile",
    standing_three_quarter: "Three-Quarter Standing",
    walking_candid: "Walking Candid Pose",
    sitting_chair: "Sitting on Chair",
    sitting_casual: "Sitting Casually",
    top_upper_portrait: "Upper Body Portrait",
    top_standing_mid: "Mid-Shot Standing",
    top_three_quarter: "3/4 Upper Body Angle",
    top_shoulder_profile: "Shoulder & Collar Focus",
    top_casual_cross: "Arms Crossed Pose",
    top_front_direct: "Direct Front Chest Shot",
    bottom_full_leg: "Waist-to-Ankle Shot",
    bottom_walking_step: "Walking Step Motion",
    bottom_side_leg: "Side Leg Profile",
    bottom_seated_cross: "Seated Leg Showcase",
    bottom_3q_lower: "3/4 Lower Body Angle",
    bottom_front_stance: "Wide Stance Stride",
    partial_face_chin_torso: "Chin to Torso Crop",
    partial_face_shoulder_profile: "Shoulder Profile Angle",
    partial_face_lips_mid: "Lips to Midsection",
    partial_face_back_shoulder: "Over Back Shoulder Angle",
    partial_face_top_collar_crop: "Collarbone & Neck Crop",
    partial_face_top_jawline_chest: "Jawline to Chest Framing",
    partial_face_top_side_profile: "Side Profile Jaw Crop",
    partial_face_top_mid_torso: "Mid-Torso Top View",
    partial_face_bottom_waist_chest: "Chest to Knee Framing",
    partial_face_bottom_hip_stride: "Hip Stride Motion Crop",
    partial_face_bottom_seated_lap: "Seated Lap Framing",
    partial_face_bottom_side_profile: "Side Lower Body Profile",
    no_face_full_body_crop: "Headless Full Body Crop",
    no_face_torso_hips_drape: "Torso & Hips Drape Focus",
    no_face_walking_stride: "Headless Walking Stride",
    no_face_seated_outfit: "Headless Seated Outfit",
    no_face_top_chest_shoulders: "Chest & Shoulders Headless",
    no_face_top_front_fit: "Direct Front Headless Fit",
    no_face_top_side_sleeve: "Side Sleeve Detail",
    no_face_top_back_detail: "Back Detail Headless View",
    no_face_bottom_waist_to_toe: "Waist-to-Toe Headless",
    no_face_bottom_side_seam: "Side Seam Fit View",
    no_face_bottom_walking_stride: "Walking Leg Stride",
    no_face_bottom_seated_trouser: "Seated Trouser Fit",
    neck_collarbone: "Neck & Collarbone Focus",
    neck_chest_portrait: "High Chest Portrait",
    neck_3q_shoulder: "3/4 Shoulder Angle",
    neck_royal_gaze: "Regal Royal Posture",
    neck_front_direct: "Direct Front Neckline",
    neck_side_drape: "Side Angle Drape",
    side_ear_profile: "Ear Profile & Jawline",
    ear_hair_tuck: "Hair Tucked Behind Ear",
    ear_head_tilt: "Gentle Head Tilt Profile",
    ear_3q_face: "3/4 Face Framing Angle",
    ear_front_balanced: "Both Ears Frontal Shot",
    ear_over_shoulder: "Over-The-Shoulder Turn",
    wrist_hand_display: "Wrist & Arm Pose",
    wrist_resting_lap: "Resting Hand on Lap",
    wrist_cross_arms: "Crossed Arms Wrist Angle",
    wrist_hand_chest: "Hand Placed Near Chest",
    wrist_side_arm: "Side Arm Extension",
    wrist_gesture: "Fluid Hand Gesture",
    hip_waist_mid: "Midsection Waist Focus",
    hip_hands_on_waist: "Hands-on-Waist 3/4 Pose",
    hip_royal_standing: "Regal Standing Waistline",
    hip_side_turn: "Side Hip Curve Angle",
    hip_saree_drape: "Saree Draped Waistline",
    hip_front_direct: "Direct Frontal Midsection",
    nose_close_profile: "Nostril Profile Focus",
    nose_front_portrait: "Direct Facial Portrait",
    nose_3q_headturn: "3/4 Head Turn Angle",
    nose_bridal_veil: "Bridal Veil Side Angle",
    nose_soft_smile: "Subtle Smile Close-Up",
    nose_macro_focus: "Ultra Macro Nosepin",
    hand_face_gesture: "Hand-to-Face Gesture",
    finger_hand_gesture: "Hand & Finger Close-Up",
    finger_chin_rest: "Hand Resting on Chin",
    finger_hands_clasped: "Hands Clasped Together",
    finger_holding_prop: "Delicate Hand Pose",
    finger_macro_ring: "Macro Ring Diamond Focus",
    finger_side_hand: "Side Profile Hand Placement",
    anklet_floor_cross_legged: "Cross-Legged Floor Pose",
    anklet_floor_legs_extended: "Floor Seated Legs Extended",
    anklet_floor_kneeling_mehendi: "Floor Kneeling / Mehendi Pose",
    anklet_ankle_close: "Lower Leg & Ankle Focus",
    anklet_step_forward: "Forward Step Motion",
    anklet_seated_foot: "Seated Foot Display Pose",
    anklet_side_foot: "Side Ankle & Heel Angle",
    anklet_both_feet: "Both Feet Draped Together",
    anklet_toering_focus: "Toe Ring & Ankle Focus",
    matha_patti: "Royal Matha Patti",
    borla: "Traditional Borla",
    passa: "Elegant Jhumar / Passa",
    headband: "Hair Headband",
    acc_forehead_tikka: "Forehead Maang Tikka Focus",
    acc_front_direct: "Direct Accessory Portrait",
    acc_3q_gaze: "3/4 Accessory Framing",
    acc_side_profile: "Side Profile Accessory Shot",
    forehead_tikka_center: "Center Forehead Tikka Focus",
    forehead_mathapatti_frame: "Full Hairline Matha Patti",
    forehead_3q_headturn: "3/4 Head Turn Angle",
    forehead_bridal_veil: "Bridal Dupatta / Veil Frame",
    forehead_side_passa: "Side Temple Passa Focus",
    forehead_front_portrait: "Direct Forehead Beauty Portrait",
    three_quarter_gaze: "Three-Quarter Elegance",
    front_direct_portrait: "Direct Frontal Portrait",
    partial_face_jawline_macro: "Macro Jawline & Ear Profile",
    partial_face_lips_collarbone: "Macro Lips to Collarbone Crop",
    partial_face_chin_neck_drape: "Chin & Neckline Drape Macro",
    partial_face_jawline_decollete: "Jawline & Décolletage Profile",
    partial_face_neck_side_throat: "Side Neck & Throat Skin Close-Up",
    partial_face_cheek_ear_close: "Cheekbone & Earlobe Macro",
    partial_face_ear_neck_profile: "Earlobe to Neck Profile",
    partial_face_hairline_ear_crop: "Hairline & Ear Framing",
    partial_face_nose_lips_profile: "Nose & Lips Profile Angle",
    partial_face_nostril_cheek_macro: "Nostril & Cheekbone Macro",
    partial_face_lips_nose_front: "Lower Face Lips & Nose Framing",
    partial_face_forehead_brows_crop: "Forehead & Eyebrow Framing",
    partial_face_hairline_temple_macro: "Hairline & Temple Profile",
    partial_face_upper_bridge_forehead: "Upper Bridge & Forehead Crop",
    partial_skin_wrist_pulse_macro: "Wrist Pulse Point Skin Macro",
    partial_skin_forearm_wrist_drape: "Forearm & Wrist Close-Up",
    partial_skin_hand_wrist_profile: "Hand Back & Wrist Joint Profile",
    partial_skin_finger_knuckle_macro: "Finger Knuckle & Ring Macro",
    partial_skin_hand_resting_skin: "Resting Hand on Skin Profile",
    partial_skin_interlocked_fingers: "Fingers Close-Up Crop",
    partial_skin_waist_hip_curve_macro: "Waist & Hip Curve Skin Macro",
    partial_skin_navel_hip_drape: "Navel & Midriff Skin Close-Up",
    partial_skin_lower_waist_profile: "Lower Waist Skin Profile",
    partial_skin_ankle_foot_macro: "Ankle Joint & Foot Skin Macro",
    partial_skin_toes_instep_close: "Toes & Instep Close-Up",
    partial_skin_heel_anklet_profile: "Heel & Anklet Profile Angle",
    partial_skin_chest_lapel_macro: "Chest & Collarbone Skin Macro",
    partial_skin_wrist_cuff_close: "Wrist & Cuff Skin Close-Up",
    no_face_neck_collarbone_drape: "Neck-to-Chest Headless Crop",
    no_face_decollete_torso: "Décolletage & Torso (No Head)",
    no_face_shoulder_back_neck: "Nape of Neck & Shoulder (No Face)",
    no_face_throat_collarbone_macro: "Throat & Collarbone Centered",
    no_face_side_neck_ear_macro: "Ear & Side Neck Angle (No Face)",
    no_face_ear_nape_profile: "Ear & Nape Rear Profile",
    no_face_shoulder_ear_line: "Earlobe to Shoulder Line (No Face)",
    no_face_wrist_hand_waist: "Wrist & Hand Resting on Waist (No Head)",
    no_face_forearm_cross_body: "Crossed Forearms over Midriff (No Head)",
    no_face_hand_lap_drape: "Hand & Wrist Draped on Lap (No Head)",
    no_face_finger_touching_hip: "Hand Resting on Hip (No Head)",
    no_face_interlocked_hands_chest: "Folded Hands on Chest (No Face)",
    no_face_finger_ring_lap: "Rings on Hand Resting on Lap (No Head)",
    no_face_waist_midriff_front: "Midriff & Navel Waistband View (Headless)",
    no_face_hip_curve_side: "Side Hip Curve & Waist Chain (No Head)",
    no_face_back_waist_drape: "Lower Back & Waistline View (No Head)",
    no_face_anklet_stepping: "Anklet & Step Motion (Legs View, No Head)",
    no_face_seated_feet_drape: "Seated Feet & Anklets View (No Head)",
    no_face_toe_ring_step: "Toe Rings & Instep Close-Up (Feet Only)",
    no_face_side_nostril_neck: "Side Nostril & Neck Angle (No Upper Face)",
    no_face_chin_lips_nose: "Lower Face Nose & Lips Angle (No Upper Head)",
    no_face_forehead_hairline_only: "Forehead & Hairline Crop (No Eyes/Face)",
    no_face_top_crown_hair: "Top Crown & Headband View (No Face)",
    no_face_chest_shoulder_accessory: "Chest & Shoulder Accessory (No Face)",
    no_face_arm_wrist_cuff: "Arm & Cuff Accessory (No Head)",
    backgroundStyle: "Background Style",
    bgColorLabel: "Background Color",
    bustDisplay: "Display Mount",
    orientationLabel: "Image Orientation",
    resolutionLabel: "Export Resolution",
    aspectRatioLabel: "Aspect Ratio",
    square: "Square",
    portrait: "Portrait",
    landscape: "Landscape",
    res_512k: "Draft Quality (512x512)",
    res_1k: "Standard HD (1024x1024)",
    res_2k: "Ultra-HD 2K (2048x2048)",
    res_4k: "Super-HD 4K (4096x4096)",
    ratio_1_1: "Square 1:1",
    ratio_3_4: "Classic 3:4",
    ratio_9_16: "Story / Reel 9:16",
    ratio_4_3: "Tablet 4:3",
    ratio_16_9: "Wide Screen 16:9",
    exportTabTitle: "Export Settings",
    exportTabSubtitle: "Configure output photo aspect ratio and resolution",
    
    // Product Choices
    saree: "Saree",
    tshirt: "T-Shirt",
    jeans: "Jeans",
    shirt: "Premium Shirt",
    western_wear: "Western Wear",
    kurta: "Kurta",
    suit: "Classic Suit",
    salwar: "Salwar Kameez",
    lehenga: "Lehenga Choli",
    gown: "Elegant Gown",
    skirt: "Stylish Skirt",
    crop_top: "Crop Top",
    blouse: "Designer Blouse",
    sherwani: "Royal Sherwani",
    dhoti: "Traditional Dhoti",
    blazer: "Premium Blazer",
    tracksuit: "Sporty Tracksuit",
    hoodie: "Cozy Hoodie",
    earrings: "Earrings",
    necklace: "Necklace",
    chain: "Elegant Chain",
    ring: "Classic Ring",
    bracelet: "Designer Bracelet",
    watch: "Luxury Watch",
    anklet: "Elegant Anklet (Payal)",
    payal: "Traditional Payal Anklet",
    toe_ring: "Designer Toe Ring (Bichhiya)",
    toe: "Toe Ring (Bichhiya)",
    nose_ring: "Designer Nose Ring",
    nose_pin: "Sparkling Nose Pin",
    nath: "Bridal Nath Nose Ring",
    nose: "Nose Pin / Ring (Nath)",
    noise: "Nose Pin / Ring (Nath)",
    waistband: "Royal Waistband (Kamarbandh)",
    hip_chain: "Elegant Hip Chain",
    kamarbandh: "Traditional Kamarbandh",
    finger_ring: "Solitaire Finger Ring",
    thumb_ring: "Stylish Thumb Ring",
    solitaire: "Diamond Solitaire Ring",
    maang_tikka: "Bridal Maang Tikka",
    bangles: "Exquisite Bangles",
    choker: "Premium Choker",
    cufflinks: "Luxury Cufflinks",
    pendant: "Classic Pendant",
    kada: "Traditional Kada",
    
    // Presentation Choices
    model: "Human Model",
    partialFace: "Human Model(Partial Face)",
    partial_face: "Human Model(Partial Face)",
    noFace: "Human Model (No Face)",
    no_face: "Human Model (No Face)",
    mannequin: "Mannequin Doll",
    hanger: "Hanger",
    ghost: "Ghost Mannequin",
    flat_lay: "Flat Lay Display",
    folded: "Folded Display",
    shelf: "Retail Shelf",
    shopwindow: "Shop Window",
    bust: "Bust Display Mount",
    
    // Gender
    male: "Male",
    female: "Female",
    no: "No",
    yes: "Yes",
    
    // Background style choices
    bg_plain: "Plain Background",
    bg_studio: "Elegant Studio",
    bg_traditional: "Traditional Indian",
    bg_festival: "Festival / Diwali",
    bg_luxury: "Luxury Marble",
    bg_wood: "Wood Table",
    bg_royal: "Royal Palace",
    bg_river: "River (Water & Rock)",
    bg_wet_sand: "Wet Sand",
    bg_nature: "Garden / Nature",
    bg_garden: "Lush Garden",
    bg_urban: "Urban Street",
    bg_vintage: "Vintage Interior",
    bg_modern_office: "Modern Office",
    bg_beach: "Sunny Beach",
    bg_velvet: "Velvet Texture",
    bg_silk: "Luxurious Silk",
    bg_granite: "Polished Granite",
    bg_mirror: "Reflective Mirror",
    
    // Regions
    head: "Head Mount",
    neck: "Neck Mount",
    wrist: "Wrist Mount",
    ankle: "Ankle Mount",
    region_finger: "Finger Stand",
    hand: "Hand Display",
    naturally: "Place Naturally",
    ear: "Ear Model",
    
    // Billing page
    apiLabel: "Google AI Gemini API Key",
    apiHelp: "Enter your personal Gemini API key. It is saved safely in your browser and is never shared.",
    saveKey: "Save Key",
    keySaved: "Key Saved Successfully!",
    validatingKey: "Saving Key...",
    keyValidated: "API Key Saved Successfully!",
    keyValidationFailed: "Invalid Key",
    enterKeyPlaceholder: "Paste your API Key (e.g. AIzaSy...)",
    pricingTitle: "Google AI Model Reference Rates",
    pricingNote: "Prices shown are Google's published baseline rates for reference. Real rates may vary.",
    estCost: "Estimated Cost per Photo",
    freeTrialActive: "API Key Required",
    activeKeyInUse: "Using Saved Personal Key",
    modelNameCol: "Model",
    resolutionCol: "Resolution",
    priceCol: "Price (Reference)",
    verifyGoogle: "Verify pricing on official Google AI pricing page",
    
    // Errors
    errNoKey: "Please save your API key in the 'Admin Panel' tab or Settings first to generate AI photos.",
    errUploadFirst: "Please upload your product photo first!",
    errGenFailed: "Failed to generate photo. Please check your internet connection or API key.",
  },
  te: {
    title: "Srushti AI",
    subtitle: "Business to Brand",
    languageToggle: "English",
    lightTheme: "పగటి వెలుతురు",
    darkTheme: "రాత్రి వెలుతురు",
    
    // Bottom Nav
    navGarment: "బట్టల ఫోటోలు",
    navJewelry: "నగల ఫోటోలు",
    navBilling: "అడ్మిన్ ప్యానెల్",
    navAdmin: "అడ్మిన్ ప్యానెల్",
    navSettings: "అమరికలు",
    
    // Garment tab labels
    garmentTitle: "బట్టల ఫోటోగ్రఫీ",
    garmentSubtitle: "చీరలు, టీ-షర్టులు, జీన్స్ మరిన్ని",
    jewelryTitle: "నగల ఫోటోగ్రఫీ",
    jewelrySubtitle: "హారాలు, చెవి కమ్మలు, గాజులు",
    billingTitle: "అడ్మిన్ ప్యానెల్ (Admin Panel)",
    adminTitle: "అడ్మిన్ ప్యానెల్ (Admin Panel)",
    billingSubtitle: "ఏఐ మోడల్ ధరలు మరియు ఏపీఐ అమరికలను నిర్వహించండి",
    adminSubtitle: "ఏఐ మోడల్ ధరలు మరియు ఏపీఐ అమరికలను నిర్వహించండి",
    settingsTitle: "యాప్ అమరికలు (Settings)",
    settingsSubtitle: "మీ ఏపీఐ కీ, యాప్ థీమ్ మరియు భాషలను ఇక్కడ సెట్ చేసుకోండి",
    settingsThemeLabel: "థీమ్ / రంగు ఎంచుకోండి",
    settingsLanguageLabel: "భాషను మార్చుకోండి (Choose Language)",
    
    // Canvas / Upload
    uploadTitle: "ఉత్పత్తి ఫోటో స్పష్టమైన ఫ్రంట్ వ్యూలో అన్ని వివరాలతో ఉండాలి",
    uploadSubtitle: "ఇక్కడ ఫోటోను వేయండి లేదా కెమెరా కోసం నొక్కండి",
    removingBg: "వెనుక బ్యాక్‌గ్రౌండ్ తీసివేయబడుతోంది...",
    removeBgSuccess: "బ్యాక్‌గ్రౌండ్ విజయవంతంగా తీసివేయబడింది!",
    removerTolerance: "తీసివేత సర్దుబాటు",
    restoreOriginal: "అసలు ఫోటో చూడండి",
    originalLabel: "అసలు ఫోటో",
    noBgLabel: "బ్యాక్‌గ్రౌండ్ లేని వస్తువు",
    finalLabel: "తయారైన ఏఐ ఫోటో",
    generating: "అందమైన ఏఐ ఫోటో తయారవుతోంది...",
    generateBtn: "ఫోటో సృష్టించు",
    retryBtn: "మళ్ళీ చేయి",
    downloadBtn: "ఫోన్‌లోకి డౌన్‌లోడ్ చేయి",
    shareBtn: "షేర్ చేయి",
    
    // Selection Headers
    productType: "వస్తువు రకం",
    presentationMode: "ప్రదర్శన విధానం",
    useModel: "మనిషి మోడల్‌కు వేయాలా?",
    genderLabel: "మోడల్ లింగం",
    poseLabel: "మోడల్ పోజ్ / కెమెరా యాంగిల్",
    standing_front: "నిలబడిన ముఖచిత్రం (ఫ్రంట్ పోజ్)",
    standing_side: "పక్క చూపు నిలబడి (సైడ్ ప్రొఫైల్)",
    standing_three_quarter: "మూడు వంతుల నిలువు భంగిమ",
    walking_candid: "నడుస్తున్నట్లుగా (క్యాండిడ్ పోజ్)",
    sitting_chair: "కుర్చీపై కూర్చుని (సిట్టింగ్ పోజ్)",
    sitting_casual: "క్యాజువల్ గా కూర్చుని",
    top_upper_portrait: "పైభాగం క్లోజ్ పోర్ట్రెయిట్",
    top_standing_mid: "నడుము వరకు నిలబడిన షాట్",
    top_three_quarter: "3/4 పైభాగం యాంగిల్",
    top_shoulder_profile: "భుజం & కొల్లార్ ఫోకస్",
    top_casual_cross: "చేతులు కట్టుకున్న శైలి",
    top_front_direct: "నేరుగా పైభాగం ఫోటో",
    bottom_full_leg: "నడుము నుండి కాళ్ళ వరకు షాట్",
    bottom_walking_step: "నడుస్తున్న కాళ్ళ ఫోకస్",
    bottom_side_leg: "పక్కకి కాళ్ళ భంగిమ",
    bottom_seated_cross: "కూర్చుని కాళ్ళు కనిపించే షాట్",
    bottom_3q_lower: "3/4 క్రింది భాగం యాంగిల్",
    bottom_front_stance: "వెడల్పుగా నిలబడిన భంగిమ",
    partial_face_chin_torso: "చిన్ నుండి టోర్సో క్రాప్",
    partial_face_shoulder_profile: "భుజం ప్రొఫైల్ కోణం",
    partial_face_lips_mid: "పెదవుల నుండి మధ్యభాగం",
    partial_face_back_shoulder: "వెనుక భుజం కోణం",
    partial_face_top_collar_crop: "మెడ మరియు కాలర్‌బోన్ క్రాప్",
    partial_face_top_jawline_chest: "దవడ నుండి ఛాతీ ఫ్రేమింగ్",
    partial_face_top_side_profile: "సైడ్ ప్రొఫైల్ జా క్రాప్",
    partial_face_top_mid_torso: "మిడ్-టోర్సో టాప్ వ్యూ",
    partial_face_bottom_waist_chest: "ఛాతీ నుండి మోకాలి ఫ్రేమింగ్",
    partial_face_bottom_hip_stride: "హిప్ స్ట్రైడ్ మోషన్ క్రాప్",
    partial_face_bottom_seated_lap: "కూర్చున్న లాప్ ఫ్రేమింగ్",
    partial_face_bottom_side_profile: "సైడ్ లోయర్ బాడీ ప్రొఫైల్",
    no_face_full_body_crop: "తల లేకుండా పూర్తి బాడీ క్రాప్",
    no_face_torso_hips_drape: "టోర్సో & హిప్స్ డ్రేప్ ఫ్యాషన్",
    no_face_walking_stride: "నడుస్తున్న స్ట్రైడ్ క్రాప్",
    no_face_seated_outfit: "కూర్చున్న దుస్తుల ఫ్రేమ్",
    no_face_top_chest_shoulders: "ఛాతీ & భుజాలు (తల లేకుండా)",
    no_face_top_front_fit: "ఫ్రంట్ ఫిట్ (తల లేకుండా)",
    no_face_top_side_sleeve: "సైడ్ స్లీవ్ డిజైన్",
    no_face_top_back_detail: "బ్యాక్ డిజైన్ (తల లేకుండా)",
    no_face_bottom_waist_to_toe: "నడుము నుండి కాళ్ళ వరకు",
    no_face_bottom_side_seam: "సైడ్ సీమ్ ఫిట్ వ్యూ",
    no_face_bottom_walking_stride: "నడుస్తున్న కాలు స్ట్రైడ్",
    no_face_bottom_seated_trouser: "కూర్చున్న ట్రౌజర్ ఫిట్",
    neck_collarbone: "మెడ & కాలర్‌బోన్ ఫోకస్",
    neck_chest_portrait: "ఎద భాగం పోర్ట్రెయిట్",
    neck_3q_shoulder: "3/4 భుజం & మెడ కోణం",
    neck_royal_gaze: "రాజసం ఉట్టిపడే మెడ భంగిమ",
    neck_front_direct: "నేరుగా హారం కనిపించే భంగిమ",
    neck_side_drape: "పక్కకి తిరిగిన హారం భంగిమ",
    side_ear_profile: "చెవి ప్రొఫైల్ & దవడ లైన్",
    ear_hair_tuck: "జుట్టు వెనక్కి దువ్విన భంగిమ",
    ear_head_tilt: "తల పక్కకి వాల్చిన భంగిమ",
    ear_3q_face: "3/4 చెవిపోగుల యాంగిల్",
    ear_front_balanced: "నేరుగా రెండు చెవులు కనిపించే షాట్",
    ear_over_shoulder: "భుజం పైనుండి చూసే భంగిమ",
    wrist_hand_display: "మణికట్టు & చేతి భంగిమ",
    wrist_resting_lap: "చేతిని హాయిగా ఆనించిన భంగిమ",
    wrist_cross_arms: "చేతులు కట్టుకుని గాజులు చూపే షాట్",
    wrist_hand_chest: "గుండె వద్ద చేయి ఉంచిన భంగిమ",
    wrist_side_arm: "పక్క చేయి చాచిన భంగిమ",
    wrist_gesture: "సున్నితమైన చేతి కదలిక",
    hip_waist_mid: "నడుము & వడ్డాణం క్లోజ్-అప్",
    hip_hands_on_waist: "నడుముపై చేతులు ఉంచిన 3/4 యాంగిల్",
    hip_royal_standing: "రాజసపు నిలబడిన వడ్డాణం షాట్",
    hip_side_turn: "పక్కకి ఒరిగిన ఒంపు భంగిమ",
    hip_saree_drape: "చీరపై వడ్డాణం కనిపించే భంగిమ",
    hip_front_direct: "నేరుగా వడ్డాణం కనిపించే షాట్",
    nose_close_profile: "ముక్కు పుడక క్లోజ్-అప్ ప్రొఫైల్",
    nose_front_portrait: "ముఖం నేరుగా చూసే ముక్కు పుడక షాట్",
    nose_3q_headturn: "3/4 తల తిరిగిన నాథ్ భంగిమ",
    nose_bridal_veil: "పెళ్ళికూతురు ముక్కు రింగ్ యాంగిల్",
    nose_soft_smile: "చిరునవ్వుతో కూడిన ముక్కు పుడక షాట్",
    nose_macro_focus: "అత్యంత క్లోజ్-అప్ ముక్కు పుడక",
    hand_face_gesture: "చేతితో ముఖం తాకే భంగిమ",
    finger_hand_gesture: "చేతి వేళ్ళు & ఉంగరం క్లోజ్-అప్",
    finger_chin_rest: "గడ్డం కింద చేయి ఆనించిన భంగిమ",
    finger_hands_clasped: "రెండు చేతులు కలిపిన ఉంగరాల షాట్",
    finger_holding_prop: "సున్నితమైన చేతి ఉంగరం భంగిమ",
    finger_macro_ring: "ఉంగరం డైమండ్ ప్రస్ఫుటమైన షాట్",
    finger_side_hand: "పక్క చేయి ఆనించిన భంగిమ",
    anklet_floor_cross_legged: "నేలపై క్రాస్-లెగ్డ్ కూర్చున్న భంగిమ",
    anklet_floor_legs_extended: "నేలపై కాళ్ళు చాపి కూర్చున్న భంగిమ",
    anklet_floor_kneeling_mehendi: "నేలపై మోకాళ్ళపై నమస్కార/మెహందీ భంగిమ",
    anklet_ankle_close: "కాలు & పట్టీలు క్లోజ్-అప్",
    anklet_step_forward: "అడుగు ముందుకు వేసిన పాయల్ భంగిమ",
    anklet_seated_foot: "కూర్చుని పట్టీలు చూపే షాట్",
    anklet_side_foot: "పక్క మడమ & పట్టీల యాంగిల్",
    anklet_both_feet: "రెండు కాళ్ళ పట్టీలు కనిపించే షాట్",
    anklet_toering_focus: "మెట్టెలు & పట్టీల క్లోజ్-అప్",
    matha_patti: "రాయల్ మాతా పట్టీ",
    borla: "సాంప్రదాయ బొర్లా",
    passa: "ఝుమర్ / పస్సా",
    headband: "తల హెడ్‌బ్యాండ్",
    acc_forehead_tikka: "పాపిడి బిళ్ళ క్లోజ్-అప్",
    acc_front_direct: "నేరుగా అలంకరణ కనిపించే భంగిమ",
    acc_3q_gaze: "3/4 అలంకరణ యాంగిల్",
    acc_side_profile: "పక్క ప్రొఫైల్ అలంకరణ షాట్",
    forehead_tikka_center: "పాపిడి బిళ్ళ క్లోజ్-అప్",
    forehead_mathapatti_frame: "మాతా పట్టీ పూర్తి హెయిర్‌లైన్ షాట్",
    forehead_3q_headturn: "3/4 తల తిరిగిన అలంకరణ భంగిమ",
    forehead_bridal_veil: "పెళ్ళికూతురు ముసుగు హెడ్‌పీస్ యాంగిల్",
    forehead_side_passa: "సైడ్ ఝుమర్ / పస్సా ప్రొఫైల్",
    forehead_front_portrait: "నేరుగా పాపిడి అలంకరణ పోర్ట్రెయిట్",
    three_quarter_gaze: "మూడు వంతుల ముఖచిత్రం",
    front_direct_portrait: "నేరుగా నిలువు ముఖచిత్రం",
    partial_face_jawline_macro: "దవడ, చెవి మాక్రో ప్రొఫైల్",
    partial_face_lips_collarbone: "పెదవులు నుండి ఎముక వరకు మాక్రో",
    partial_face_chin_neck_drape: "గడ్డం, మెడ లైన్ క్లోజప్",
    partial_face_jawline_decollete: "దవడ, ఛాతీ పైభాగ ప్రొఫైల్",
    partial_face_neck_side_throat: "ప్రక్క మెడ చర్మం మాక్రో",
    partial_face_cheek_ear_close: "చెంప, చెవి లంబిక మాక్రో",
    partial_face_ear_neck_profile: "చెవి లంబిక నుండి మెడ ప్రొఫైల్",
    partial_face_hairline_ear_crop: "జుట్టు పక్కన చెవి ఫ్రేమింగ్",
    partial_face_nose_lips_profile: "ముక్కు, పెదవుల ప్రొఫైల్",
    partial_face_nostril_cheek_macro: "ముక్కురంధ్రం, చెంప మాక్రో",
    partial_face_lips_nose_front: "కింది ముఖం, ముక్కు ఫ్రేమింగ్",
    partial_face_forehead_brows_crop: "నుదురు, కనుబొమ్మల ఫ్రేమింగ్",
    partial_face_hairline_temple_macro: "పాపిడి, కణత ప్రొఫైల్",
    partial_face_upper_bridge_forehead: "నుదురు పైభాగం మాక్రో",
    partial_skin_wrist_pulse_macro: "చేతి మణికట్టు చర్మం మాక్రో",
    partial_skin_forearm_wrist_drape: "మొచేయి, మణికట్టు క్లోజప్",
    partial_skin_hand_wrist_profile: "అరచేతి వెనుక ప్రొఫైల్",
    partial_skin_finger_knuckle_macro: "వేలి కణుపు, ఉంగరం మాక్రో",
    partial_skin_hand_resting_skin: "చర్మంపై చేయి ప్రొఫైల్",
    partial_skin_interlocked_fingers: "వేళ్ళ క్లోజప్ ఫ్రేమింగ్",
    partial_skin_waist_hip_curve_macro: "నడుము మలుపు చర్మం మాక్రో",
    partial_skin_navel_hip_drape: "బొడ్డు, నడుము చర్మం క్లోజప్",
    partial_skin_lower_waist_profile: "కింది నడుము చర్మం ప్రొఫైల్",
    partial_skin_ankle_foot_macro: "మడమ, పాదం చర్మం మాక్రో",
    partial_skin_toes_instep_close: "కాలి వేళ్ళు, పాదం క్లోజప్",
    partial_skin_heel_anklet_profile: "మడమ, పట్టీ ప్రొఫైల్",
    partial_skin_chest_lapel_macro: "ఛాతీ, ఎముక చర్మం మాక్రో",
    partial_skin_wrist_cuff_close: "మణికట్టు, కఫ్ చర్మం క్లోజప్",
    no_face_neck_collarbone_drape: "గడ్డం కింద నుండి ఛాతీ దాకా ఫ్రేమింగ్",
    no_face_decollete_torso: "ఛాతీ మరియు డెకోలేటే ఫ్రేమ్ (తల లేదు)",
    no_face_shoulder_back_neck: "మెడ వెనుక మరియు భుజం వ్యూ",
    no_face_throat_collarbone_macro: "మెడ, కాలర్‌బోన్ సెంటర్డ్ వ్యూ",
    no_face_side_neck_ear_macro: "చెవి, ప్రక్క మెడ యాంగిల్ (ముఖం లేదు)",
    no_face_ear_nape_profile: "చెవి, పిలక ప్రక్క ప్రొఫైల్",
    no_face_shoulder_ear_line: "చెవి నుండి భుజం వరకు వ్యూ",
    no_face_wrist_hand_waist: "నడుముపై చేయి, మణికట్టు ఫ్రేమింగ్",
    no_face_forearm_cross_body: "పొట్ట వద్ద అడ్డంగా ఉన్న చేతులు",
    no_face_hand_lap_drape: "తొడలపై ఉన్న మణికట్టు, చేతులు",
    no_face_finger_touching_hip: "నడుముపై వేళ్ళు మరియు ఉంగరం",
    no_face_interlocked_hands_chest: "ఛాతీపై మడిచిన చేతులు, వేళ్ళు",
    no_face_finger_ring_lap: "తొడపై అమర్చిన ఉంగరాల చేతి వ్యూ",
    no_face_waist_midriff_front: "నడుము, బొడ్డు భాగం (హెడ్‌లెస్)",
    no_face_hip_curve_side: "ప్రక్క నడుము మలుపు వ్యూ (తల లేదు)",
    no_face_back_waist_drape: "వీపు కింది భాగం నడుము పట్టీ",
    no_face_anklet_stepping: "కాలి పట్టీ మరియు నడక స్టెప్ (కాళ్ళ వ్యూ)",
    no_face_seated_feet_drape: "కూర్చున్న పాదాలు, పట్టీల వ్యూ",
    no_face_toe_ring_step: "కాలి వేళ్ళు, మెట్టెల క్లోజప్",
    no_face_side_nostril_neck: "ముక్కురంధ్రం, మెడ యాంగిల్",
    no_face_chin_lips_nose: "పెదవులు, ముక్కు కింద భాగం",
    no_face_forehead_hairline_only: "నుదురు, పాపిడి వ్యూ (కళ్ళు లేవు)",
    no_face_top_crown_hair: "తల పైభాగం హేర్‌బ్యాండ్ వ్యూ",
    no_face_chest_shoulder_accessory: "ఛాతీ, భుజాల యాక్సెసరీ వ్యూ",
    no_face_arm_wrist_cuff: "చేయి, కఫ్ యాక్సెసరీ వ్యూ",
    backgroundStyle: "వెనుక బ్యాక్‌గ్రౌండ్ రకం",
    bgColorLabel: "బ్యాక్‌గ్రౌండ్ రంగు",
    bustDisplay: "డిస్ప్లే స్టాండ్ రకం",
    orientationLabel: "చిత్రం ఓరియంటేషన్ / దిశ",
    resolutionLabel: "ఎగుమతి రిజల్యూషన్ (క్వాలిటీ)",
    aspectRatioLabel: "యాస్పెక్ట్ రేషియో (పరిమాణం)",
    square: "చతురస్రం",
    portrait: "నిలువు",
    landscape: "అడ్డంగా",
    res_512k: "తక్కువ క్వాలిటీ (512x512)",
    res_1k: "సాధారణ నాణ్యత HD (1024x1024)",
    res_2k: "అధిక నాణ్యత 2K (2048x2048)",
    res_4k: "అత్యంత స్పష్టత 4K (4096x4096)",
    ratio_1_1: "చదరం 1:1",
    ratio_3_4: "క్లాసిక్ 3:4",
    ratio_9_16: "రీల్ / స్టోరీ 9:16",
    ratio_4_3: "టాబ్లెట్ 4:3",
    ratio_16_9: "వెడల్పు స్క్రీన్ 16:9",
    exportTabTitle: "ఎగుమతి అమరికలు",
    exportTabSubtitle: "ఫైనల్ ఫోటో యొక్క సైజ్ మరియు క్వాలిటీ సెట్ చేసుకోండి",
    
    // Product Choices
    saree: "చీర",
    tshirt: "టీ-షర్ట్",
    jeans: "జీన్స్",
    shirt: "ప్రీమియం షర్ట్",
    western_wear: "వెస్ట్రన్ వేర్",
    kurta: "కుర్తా",
    suit: "క్లాసిక్ సూట్",
    salwar: "సల్వార్ కమీజ్",
    lehenga: "లెహంగా చోళీ",
    gown: "గౌన్",
    skirt: "స్కార్ట్",
    crop_top: "క్రాప్ టాప్",
    blouse: "బ్లౌజ్",
    sherwani: "షేర్వాణీ",
    dhoti: "సాంప్రదాయ ధోతి",
    blazer: "బ్లేజర్",
    tracksuit: "ట్రాక్‌సూట్",
    hoodie: "హుడీ",
    earrings: "కమ్మలు (చెవి రింగులు)",
    necklace: "నెక్లెస్ / హారం",
    chain: "మెడ గొలుసు (చైన్)",
    ring: "ఉంగరం (రింగ్)",
    bracelet: "చేతి కడియం (బ్రేస్లెట్)",
    watch: "చేతి గడియారం (వాచ్)",
    anklet: "పట్టీలు (ఆంక్లెట్ / పాయల్)",
    payal: "సాంప్రదాయ పాయల్ పట్టీలు",
    toe_ring: "మెట్టెలు (బొటనవేలు ఉంగరం)",
    toe: "మెట్టెలు (కాలినవేలు ఉంగరం)",
    nose_ring: "ముక్కు పుడక / రింగ్",
    nose_pin: "మెరిసే ముక్కు పుడక",
    nath: "పెళ్ళికూతురు నాథ్ (ముక్కు రింగ్)",
    nose: "ముక్కు పుడక / ముక్కు రింగ్",
    noise: "ముక్కు పుడక / ముక్కు రింగ్",
    waistband: "వడ్డాణం (నడుము పట్టి)",
    hip_chain: "నడుము గొలుసు (హిప్ చైన్)",
    kamarbandh: "సాంప్రదాయ కమర్‌బంద్",
    finger_ring: "చేతి వేలు ఉంగరం (ఫింగర్ రింగ్)",
    thumb_ring: "బొటనవేలు ఉంగరం (థంబ్ రింగ్)",
    solitaire: "సోలిటైర్ డైమండ్ రింగ్",
    maang_tikka: "పాపిడి బిళ్ళ (మాంగ్ తిక్కా)",
    bangles: "గాజులు (బ్యాంగిల్స్)",
    choker: "చోకర్ హారం",
    cufflinks: "కఫ్ లింకులు",
    pendant: "లాకెట్ / పెండెంట్",
    kada: "కడా / బ్రేస్‌లెట్",
    
    // Presentation Choices
    model: "మనిషి మోడల్",
    partialFace: "మానవ మోడల్ (పాక్షిక ముఖం)",
    partial_face: "మానవ మోడల్ (పాక్షిక ముఖం)",
    noFace: "మానవ మోడల్ (ముఖం లేకుండా)",
    no_face: "మానవ మోడల్ (ముఖం లేకుండా)",
    mannequin: "బొమ్మ (మెనకిన్)",
    hanger: "హ్యాంగర్ స్టాండ్",
    ghost: "అదృశ్య బొమ్మ",
    flat_lay: "ఫ్లాట్ లే డిజైన్",
    folded: "మడతపెట్టిన ప్రదర్శన",
    shelf: "రిటైల్ షెల్ఫ్",
    shopwindow: "షాప్ విండో",
    bust: "ఆభరణాల స్టాండ్",
    
    // Gender
    male: "పురుషుడు",
    female: "స్త్రీ",
    no: "వద్దు",
    yes: "అవును",
    
    // Background style choices
    bg_plain: "సాధారణ రంగు",
    bg_studio: "స్టూడియో లైటింగ్",
    bg_traditional: "భారతీయ సాంప్రదాయం",
    bg_festival: "పండుగ / దీపావళి వెలుగులు",
    bg_luxury: "లగ్జరీ మార్బుల్ నేల",
    bg_wood: "చెక్క బల్ల",
    bg_royal: "రాజభవనం",
    bg_river: "నది (నీరు & రాయి)",
    bg_wet_sand: "తడి ఇసుక (Wet Sand)",
    bg_nature: "తోట / ప్రకృతి వాతావరణం",
    bg_garden: "పూల తోట (గార్డెన్)",
    bg_urban: "నగర వీధి (అర్బన్)",
    bg_vintage: "పాతకాలపు గది (వింటేజ్)",
    bg_modern_office: "ఆధునిక ఆఫీస్",
    bg_beach: "బీచ్ వాతావరణం",
    bg_velvet: "వెల్వెట్ బ్యాక్‌గ్రౌండ్",
    bg_silk: "పట్టు వస్త్రం (సిల్క్)",
    bg_granite: "గ్రానైట్ నేల",
    bg_mirror: "అద్దం ప్రతిబింబం",
    
    // Regions
    head: "తల భాగం",
    neck: "మెడ భాగం",
    wrist: "మణికట్టు భాగం",
    ankle: "కాలి మడమ భాగం",
    region_finger: "వేలి భాగం",
    hand: "చేతి భాగం",
    naturally: "సహజంగా ఉంచండి (Place Naturally)",
    ear: "చెవి భాగం",
    
    // Billing page
    apiLabel: "గూగుల్ ఏఐ జెమిని ఏపీఐ కీ",
    apiHelp: "మీ జెమిని ఏపీఐ కీ ఇక్కడ రాయండి. ఇది మీ ఫోన్‌లో సురక్షితంగా ఉంటుంది, ఎవరికీ తెలియదు.",
    saveKey: "కీని సేవ్ చేయి",
    keySaved: "కీ సేవ్ చేయబడింది!",
    validatingKey: "కీని సేవ్ చేస్తోంది...",
    keyValidated: "ఏపీఐ కీ విజయవంతంగా సేవ్ చేయబడింది!",
    keyValidationFailed: "చెల్లని కీ (Invalid Key)",
    enterKeyPlaceholder: "ఇక్కడ కీని పేస్ట్ చేయండి (ఉదా: AIzaSy...)",
    pricingTitle: "గూగుల్ ఏఐ మోడల్ ధరల పట్టిక",
    pricingNote: "ఈ ధరలు కేవలం గూగుల్ ప్రచురించిన ప్రాథమిక వివరాలు మాత్రమే. అసలు ధరలు మారవచ్చు.",
    estCost: "ఒక ఫోటో తయారీ అంచనా ఖరీదు",
    freeTrialActive: "ఏపీఐ కీ అవసరం (API Key Required)",
    activeKeyInUse: "మీ వ్యక్తిగత కీ ఉపయోగించబడుతోంది",
    modelNameCol: "మోడల్",
    resolutionCol: "రిజల్యూషన్",
    priceCol: "ధర (డాలర్లలో)",
    verifyGoogle: "గూగుల్ అధికారిక ధరల వెబ్‌సైట్‌లో సరిచూసుకోండి",
    
    // Errors
    errNoKey: "ఏఐ ఫోటోలు చేయడానికి ముందు దయచేసి 'అడ్మిన్ ప్యానెల్' లేదా సెట్టింగ్‌లలో మీ ఏపీఐ కీని సేవ్ చేసుకోండి.",
    errUploadFirst: "ముందుగా మీ వస్తువు ఫోటోను అప్‌లోడ్ చేయండి!",
    errGenFailed: "ఫోటో తయారుచేయడం కుదరలేదు. దయచేసి ఇంటర్నెట్ లేదా ఏపీఐ కీని సరిచూసుకోండి.",
  }
};

// Map selection configurations to english keywords for background prompting
export const PROMPT_FRAGMENTS = {
  garment: {
    types: {
      saree: "a luxurious traditional Indian silk saree with exquisite border embroidery",
      tshirt: "a modern casual cotton t-shirt with great fit and clean texture",
      jeans: "a classic stylish denim jeans trouser with premium cotton texture",
      shirt: "a tailored premium casual cotton button-down shirt with elegant collar design",
      western_wear: "a high-fashion chic western wear full outfit, sophisticated modern dress or contemporary co-ord apparel set with impeccable tailoring, fluid drapery, and elegant urban styling",
      kurta: "a traditional Indian premium cotton kurta with subtle elegant embroidery",
      suit: "a sharp handsome bespoke tailored classic two-piece suit with sleek lapels",
      salwar: "an elegant traditional salwar kameez suit with beautiful dupatta drape",
      lehenga: "a stunning traditional bridal lehenga choli with heavy golden embroidery and flowing dupatta",
      gown: "a breathtaking, flowing modern evening gown with elegant fabric draping and premium couture feel",
      skirt: "a fashionable stylish casual flared skirt with subtle pleat details and beautiful textile print",
      crop_top: "a trendy chic crop top with elegant neckline, modern silhouette and fine stitching",
      blouse: "an exquisitely embroidered designer Indian saree blouse with artistic back-neck patterns",
      sherwani: "a magnificent royal Indian sherwani with intricate handwoven Zardozi embroidery, regal wedding wear",
      dhoti: "a pristine traditional Indian dhoti paired elegantly with a rich ethnic silk border",
      blazer: "a premium tailored modern slim-fit blazer with elegant fabric sheen and crisp lapels",
      tracksuit: "a stylish modern athletic fleece tracksuit with precise fits and clean sporty panelling",
      hoodie: "a cozy premium organic cotton pullover hoodie with relaxed fit and soft luxurious textile finish"
    },
    presentations: {
      model: {
        male: "worn elegantly by a handsome, professional young Indian male fashion model with a neutral high-fashion expression, never smiling",
        female: "worn gracefully by a beautiful, professional young Indian female fashion model with a neutral high-fashion expression, never smiling"
      },
      mannequin: {
        male: "displayed on a modern high-end realistic studio showroom clothing male mannequin",
        female: "displayed on a modern high-end realistic studio showroom clothing female mannequin"
      },
      hanger: "hanging neatly on a minimalist wooden hanger in a beautiful high-end boutique wardrobe",
      ghost: "photographed in flat lay ghost mannequin style, 3D hollow garment fit showing inner lining",
      flat_lay: "perfectly arranged in a professional fashion flat-lay style on a clean neutral studio board",
      folded: "folded immaculately in a clean neat square shape in high-end luxury retail boutique style on a flat surface, with the main signature feature, pallu, collar, chest embroidery, or primary decorative motif prominently visible on top facing directly up towards the camera",
      shelf: "placed beautifully on a minimalist floating boutique retail shelf, warm soft spot lighting",
      shopwindow: "featured in a premium luxury high-street showroom window display glass showcase box"
    },
    poses: {
      standing_front: "standing straight in a polished professional catalog front pose (face fully shown in clean catalog alignment)",
      standing_side: "standing in an elegant three-quarter side profile showcase pose (face fully shown in 3/4 side profile view)",
      standing_three_quarter: "standing in an elegant three-quarter angle studio catalog pose (face fully shown in studio gaze)",
      walking_candid: "captured in a dynamic, stylish walking candid street style pose (face fully shown in natural candid movement)",
      sitting_chair: "sitting elegantly on a stylish studio chair in a professional catalog pose (face fully shown in poised sitting posture)",
      sitting_casual: "sitting in a casual, relaxed lounge style posture, natural poise (face fully shown)",
      top_upper_portrait: "high-chest portrait framing upper garment and shoulders (face fully shown centered in frame)",
      top_standing_mid: "standing mid-length portrait framing torso down to hips (face fully shown with poised posture)",
      top_three_quarter: "three-quarter upper body studio angle (face fully shown in 3/4 turn)",
      top_shoulder_profile: "side profile shoulder angle showcasing neckline and sleeve cut (face fully shown in side profile view)",
      top_casual_cross: "casual crossed-arms posture highlighting chest and fit (face fully shown directly facing camera)",
      top_front_direct: "direct frontal torso alignment with symmetrical shoulders (face fully shown in frontal symmetry)",
      bottom_full_leg: "waist-to-ankle shot showcasing leg silhouette, trousers, or skirt (face partially shown or cropped above waist depending on framing height)",
      bottom_walking_step: "walking step motion highlighting pant drape and footwear (face partially shown or cropped above waist)",
      bottom_side_leg: "side leg profile showcasing waistline, pockets, and side seams (face partially shown / lower body focus)",
      bottom_seated_cross: "seated leg showcase with crossed knees displaying fabric stretch (face partially or fully shown in relaxed seating)",
      bottom_3q_lower: "three-quarter lower body catalog angle (face partially shown or cropped near chest)",
      bottom_front_stance: "wide stance stride showcasing fit across hips and thighs (face partially or fully shown depending on vertical crop)"
    },
    backgrounds: {
      plain: (color: string) => `against a clean seamless minimalist solid plain ${color || "studio light gray"} background with soft shadow`,
      studio: "in a high-end luxury fashion photography studio, professional softbox three-point lighting, subtle shadows, professional editorial style",
      traditional: "inside an elegant, beautifully lit rich Indian courtyard, traditional arch design, warm light, premium ethnic background",
      festival: "decorated for Diwali festival, surrounded by warm glittering bokeh lights, glowing clay oil lamps (diyas), elegant traditional backdrop",
      luxury: "on a magnificent polished Italian white marble floor with luxurious golden accents and elegant reflection",
      royal: "in front of an ornate royal palace balcony at sunset, soft warm golden hour light, majestic heritage Indian setting",
      urban: "against a fashionable chic downtown urban brick wall background with modern street cafe vibe, soft natural daylight",
      vintage: "inside a magnificent vintage Indian palace room, featuring hand-carved heritage arches, antique royal wooden columns, vintage brass chandeliers, and soft atmospheric golden light filtering through ornamental windows",
      modern_office: "inside a clean high-end architectural corporate office space with large windows and a beautiful city skyline background"
    }
  },
  jewelry: {
    types: {
      earrings: "a pair of magnificent sparkling gold diamond chandelier earrings, highly detailed traditional Indian jewelry craftsmanship",
      necklace: "a breathtaking royal gold choker necklace with emeralds and pearls, elaborate traditional Indian jewelry masterwork",
      chain: "an elegant sparkling precious metal chain necklace, refined design and beautiful luxury polish",
      ring: "a stunning sparkling gold diamond ring, displaying expert craftsmanship and brilliant reflections",
      bracelet: "a luxury designer hand bracelet with intricately crafted patterns and brilliant precious gemstones",
      watch: "a high-end luxury mechanical wrist watch with fine craftsmanship, shining metallic finish and premium detailing",
      anklet: "a delicate designer bridal gold anklet (payal) adorned with tiny pearls, silver ghungroo bells, and intricate ethnic handwork",
      payal: "an elaborate traditional Indian payal anklet pair with shimmering silver ghungroo bells and delicate chainwork",
      toe_ring: "a delicate pair of traditional gold and silver toe rings (bichhiya) with intricate floral engravings",
      toe: "a delicate pair of traditional gold and silver toe rings (bichhiya / toe jewelry) with intricate filigree and gemstone accents",
      nose_ring: "a traditional Indian bridal nose ring (nath) with dangling pearls and elegant thin gold wire loops",
      nose_pin: "a brilliant diamond-studded nose pin with subtle gold filigree, delicate and radiant",
      nath: "an ornate traditional Indian bridal nath nose ring with a delicate pearl chain and dangling ruby drop",
      nose: "a traditional Indian bridal nose pin or nose ring (nath) with dangling pearls, delicate filigree, and elegant gold wire loops",
      noise: "a traditional Indian bridal nose pin or nose ring (nath) with dangling pearls, delicate filigree, and elegant gold wire loops",
      waistband: "an intricate royal gold waistband (vaddanam/kamarbandh) with temple art motifs, ruby accents, and dangling gold beads",
      hip_chain: "a delicate sparkling multi-layered gold hip chain resting gracefully on waist drapes",
      kamarbandh: "a regal traditional Indian kamarbandh waist belt studded with Kundan gemstones and pearls",
      finger_ring: "a magnificent diamond finger ring with intricate filigree band and brilliant solitaire centerpiece",
      thumb_ring: "a bold stylish gold thumb ring with carved vintage patterns and high-polish finish",
      solitaire: "a breathtaking platinum solitaire diamond ring with a brilliant round-cut central diamond",
      maang_tikka: "a breathtaking traditional Indian bridal maang tikka hair ornament with Kundan stones and pearl drops",
      matha_patti: "a regal Kundan gold matha patti framing the hairline and forehead with intricate gemstone drapes",
      borla: "a traditional Rajasthani gold spherical borla positioned elegantly on the upper center forehead",
      passa: "a luxurious Mughal-style gold pearls jhumar passa pinned gracefully to the side of the head",
      headband: "a delicate diamond and gold hair headband framing the forehead and crown",
      bangles: "a set of breathtaking gold bangles with colorful enamel work (meenakari) and brilliant gemstone settings",
      choker: "a stunning high-fashion choker necklace with layered rows of precious rubies and high-polish gold bars",
      cufflinks: "a pair of ultra-premium gold cufflinks with mother-of-pearl inserts, reflecting clean geometric luxury",
      pendant: "a delicate gold chain with a magnificent teardrop emerald pendant reflecting beautiful crystal facets",
      kada: "a heavy traditional Punjabi kada bracelet made of polished silver and solid gold with ancient royal engravings"
    },
    presentations: {
      model: {
        male: "worn elegantly by a handsome, stylish Indian male model with a neutral high-fashion expression, never smiling, close-up luxury portrait, clean skin",
        female: "worn gracefully by a beautiful young Indian woman with a neutral high-fashion expression, never smiling, with elegant hair bun, highlighting the fine details of the jewelry, warm classic lighting"
      },
      bust: {
        head: "mounted on a luxury black velvet jewelry mannequin head display stand, pristine showcase",
        neck: "elegantly presented on a high-end modern concrete jewelry neck bust model display stand",
        wrist: "wrapped neatly on a modern luxury soft leather cushion jewelry wrist display bolster",
        ankle: "displayed gracefully on a realistic designer white ceramic ankle display mount, showcasing pristine jewelry details",
        finger: "slid beautifully onto a minimalist polished wooden ring cone holder display stand",
        hand: "worn and perfectly fitted onto the finger of an artistic matte-finish porcelain female hand sculpture jewelry display stand",
        naturally: "placed naturally, organically, and seamlessly within the surrounding background environment without any artificial stands or display mounts, resting physically on background surfaces with authentic contact shadows, surface reflections, and matching scene lighting",
        ear: "displayed on a modern gold-plated T-bar ear profile jewelry display stand"
      }
    },
    poses: {
      neck_collarbone: "in an intimate macro close-up portrait focusing on the neck, collarbone, and neckline (face partially shown — cropped cleanly from chin/lower lip to chest, emphasizing necklace drape)",
      neck_chest_portrait: "in a high chest beauty portrait framing neckwear over collarbone and upper chest (face fully shown or lower face framed cleanly above necklace)",
      neck_3q_shoulder: "in a three-quarter shoulder turn highlighting neckwear angle and shoulder drape (face fully shown in 3/4 beauty angle)",
      neck_royal_gaze: "in a regal posture looking slightly upward into golden studio light (face fully shown with serene gaze)",
      neck_front_direct: "in a direct frontal close-up framing symmetrical necklace and collarbone (face fully shown or lower face framed in direct symmetry)",
      neck_side_drape: "in a side profile neck drape angle showcasing clasp and side links (face partially shown in side profile focusing on neck and jawline)",
      side_ear_profile: "in an elegant side profile angle highlighting earlobe, jawline, and neck (face partially shown in side profile, focusing on ear and cheekbone)",
      ear_hair_tuck: "with hair tucked behind ear revealing dangling earring details (face fully or partially shown in side profile angle)",
      ear_head_tilt: "with a gentle head tilt showcasing earring drop length (face fully shown with graceful head angle)",
      ear_3q_face: "in a three-quarter face turn framing earring and cheek contour (face fully shown in 3/4 beauty gaze)",
      ear_front_balanced: "in a direct frontal portrait displaying both dangling earrings symmetrically (face fully shown centered in frame)",
      ear_over_shoulder: "in an over-the-shoulder glance highlighting ear profile and jawline (face partially shown in over-the-shoulder view)",
      wrist_hand_display: "in a refined close-up gesture focusing on hand, wrist, and forearm placement (face partially shown — softly blurred or cropped above chest, prioritizing wrist accessories)",
      wrist_resting_lap: "with hands resting gracefully on lap showcasing bracelets and bangles (face partially shown / lower torso frame)",
      wrist_cross_arms: "in a crossed arms posture highlighting wrist accessories over sleeves (face fully or partially shown in confident pose)",
      wrist_hand_chest: "with hand placed near chest/collarbone bringing wrist and rings near neckline (face fully shown with hand touching chest)",
      wrist_side_arm: "in a side arm extension highlighting watch dial or bangle stack (face partially shown / focused on forearm and wrist)",
      wrist_gesture: "in a fluid hand gesture in mid-motion showcasing sparkling wristwear (face fully or partially shown in background)",
      hip_waist_mid: "in a midsection waist focus framing waistline ornament over ethnic drapes (face partially shown — cropped near lower ribs or chin, prioritizing waistline)",
      hip_hands_on_waist: "with hands on waist in three-quarter pose framing hip chain (face fully or partially shown)",
      hip_royal_standing: "in a regal standing posture showcasing full waistline and lower apparel (face fully shown with tall posture)",
      hip_side_turn: "in a side hip curve angle accentuating waist belt drapes (face partially or fully shown in side angle)",
      hip_saree_drape: "in a saree draped waistline shot focusing on central motif (face fully or partially shown)",
      hip_front_direct: "in a direct frontal midsection alignment centering hip ornament (face partially shown / lower torso focus)",
      nose_close_profile: "in a nostril profile focus close-up highlighting delicate nath loop and pearl drop (face partially shown — close macro focus on nose, lips, and cheek)",
      nose_front_portrait: "in a direct frontal facial beauty portrait framing nose ring and lips (face fully shown in direct symmetry)",
      nose_3q_headturn: "in a three-quarter head turn capturing nath chain connecting to hair (face fully shown in 3/4 turn)",
      nose_bridal_veil: "in a bridal veil side angle with sheer dupatta framing nose ring and eyes (face partially shown / softly veiled)",
      nose_soft_smile: "in a subtle smile close-up accentuating nose pin shimmer near lips (face fully shown with gentle expression)",
      nose_macro_focus: "in an ultra macro nosepin focus centering the nose ornament (face partially shown — tight macro crop on nose and cheek)",
      finger_hand_gesture: "in a hand and finger close-up gesture displaying rings on manicured fingers (face partially shown — softly blurred or cropped above chest)",
      finger_chin_rest: "with hand softly resting on chin/cheek highlighting ring on finger near lips (face fully shown with hand touching chin)",
      finger_hands_clasped: "with hands clasped together in front of chest showcasing multiple rings (face fully or partially shown)",
      finger_holding_prop: "in a delicate hand pose holding silk fabric showcasing ring facets (face partially shown / focus on hand and ring)",
      finger_macro_ring: "in a macro focus on solitaire diamond ring on finger (face partially shown / macro focus on hand)",
      finger_side_hand: "in a side profile hand placement highlighting ring band detail (face partially shown / focus on hand profile)",
      anklet_floor_cross_legged: "seated cross-legged on a polished wooden/marbled floor, with legs neatly folded displaying payal drapes and toe ring details (lower body / feet close-up focus)",
      anklet_floor_legs_extended: "sitting gracefully on the floor with legs extended forward, displaying shimmering anklet chains and intricate toe rings resting gently on smooth floor (feet and lower leg focus)",
      anklet_floor_kneeling_mehendi: "kneeling gracefully on a rich carpeted or marble floor, top-down angle capturing payal chainwork, ghungroo drops, and shimmering toe rings against floor decor",
      anklet_ankle_close: "in a lower leg and ankle focus close-up showcasing payal and ghungroo bells (face partially shown — strictly lower leg focus, face cropped out of frame)",
      anklet_step_forward: "in a forward step motion highlighting anklet drape on foot (face partially shown — lower body/feet focus, face cropped out)",
      anklet_seated_foot: "in a seated foot display pose with foot resting on cushion (face partially shown — feet and lower leg focus)",
      anklet_side_foot: "in a side ankle and heel angle showcasing delicate chainwork (face partially shown — foot and ankle focus)",
      anklet_both_feet: "with both feet draped together displaying pair of payals (face partially shown — feet focus)",
      anklet_toering_focus: "in a toe ring and ankle focus close-up (face partially shown — feet and toes focus)",
      forehead_tikka_center: "in a close-up direct forehead and hairline beauty shot, highlighting center-placed maang tikka or borla (face fully shown — centered on upper face, eyes, and forehead)",
      forehead_mathapatti_frame: "in a frontal beauty portrait framing full forehead and hairline, displaying elaborate Kundan matha patti craftsmanship (face fully shown in frontal beauty portrait)",
      forehead_3q_headturn: "in a three-quarter head turn angle showcasing forehead ornament, temple detailing, and facial contouring (face fully shown in 3/4 angle)",
      forehead_bridal_veil: "in a side angle bridal portrait with sheer dupatta framing forehead ornament and eyes (face partially shown / veiled face with eyes and forehead clear)",
      forehead_side_passa: "in a side profile head angle highlighting passa / jhumar draped gracefully over temple and hair (face partially shown in side profile focusing on temple and hair)",
      forehead_front_portrait: "in a symmetrical front-facing beauty portrait centering forehead jewelry, eyes, and regal poise (face fully shown in regal symmetry)",
      acc_forehead_tikka: "in a forehead maang tikka focus shot (face fully shown framing forehead and eyes)",
      acc_front_direct: "in a direct accessory portrait in direct frontal symmetry (face fully shown)",
      acc_3q_gaze: "in a three-quarter accessory framing angle (face fully shown in 3/4 gaze)",
      acc_side_profile: "in a side profile accessory shot (face partially or fully shown in side profile)",
      hand_face_gesture: "in a graceful beauty pose with manicured hand and fingers softly resting near the cheek or chin (face fully shown in beauty portrait)",
      three_quarter_gaze: "in a classic three-quarter high-fashion beauty portrait with a subtle head tilt and serene gaze (face fully shown in 3/4 high-fashion gaze)",
      front_direct_portrait: "in a regal direct-facing portrait looking into the camera with poised confidence (face fully shown looking directly into camera)"
    },
    backgrounds: {
      plain: (color: string) => `against a solid minimalist clean plain background of ${color || "soft cream"} with professional jewelry soft drop shadow`,
      studio: "under crisp professional macro jewelry studio lighting, high contrast reflections, flawless metallic sparkle, magazine commercial shot",
      luxury: "placed elegantly on a slab of dark veins luxury marble, scattered gold flakes, soft reflections, premium catalog look",
      festival: "with a warm glowing festive background, soft burning brass lamps, traditional marigold flowers, soft warm bokeh",
      traditional: "resting on an antique royal Indian hand-carved copper tray, rich silks in the soft-focus background, historical maharaja aesthetic",
      wood: "placed beautifully on a rustic dark polished solid teak wood table, with soft warm side-lighting, organic and premium feel",
      beach: "placed on fine golden sand in a photographic frame composition of sand, warm coastal sunlight",
      velvet: "nestled inside a luxurious deep-crimson velvet textile fabric background, creating beautiful contrast and high-fashion editorial aura",
      silk: "resting gracefully on a drape of pure royal-blue silk saree cloth, reflecting soft warm light and magnificent texture",
      granite: "placed elegantly on a slab of rough-textured polished black granite stone, with architectural side spotlight shadows",
      mirror: "placed on a polished dark reflective mirror plate, capturing a flawless symmetric luxury reflection under dim atmospheric warm lighting"
    }
  }
};
